-- ⚠️ AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
-- This migration is generated by a script in backend/scripts/migrations/.
-- To make changes, edit the generator script and re-run it.
-- The user will handle migration generation and application.
--
-- UNLOGGED Tables Setup
-- Converts ephemeral counter/rate-limit tables to UNLOGGED (skip WAL writes).
-- Idempotent: only alters tables not already UNLOGGED.
-- Gracefully skips if required roles are not yet created.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'runtime_role') THEN
    RAISE NOTICE 'Skipping UNLOGGED setup - roles not available.';
    RETURN;
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'rate_limits') != 'u' THEN
    ALTER TABLE rate_limits SET UNLOGGED;
    RAISE NOTICE 'rate_limits set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'user_counters') != 'u' THEN
    ALTER TABLE user_counters SET UNLOGGED;
    RAISE NOTICE 'user_counters set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'channel_counters') != 'u' THEN
    ALTER TABLE channel_counters SET UNLOGGED;
    RAISE NOTICE 'channel_counters set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'product_counters') != 'u' THEN
    ALTER TABLE product_counters SET UNLOGGED;
    RAISE NOTICE 'product_counters set to UNLOGGED';
  END IF;

  RAISE NOTICE 'UNLOGGED setup complete.';
END $$;
