---
packages:
  - backend
  - cdc
  - shared
  - cli/*
  - frontend
  - locales
  - studio

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  eslint@<9.26.0: '>=9.26.0'
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'