/**
 * Drizzle Migration Utilities (v1 format)
 *
 * Shared utilities for programmatically managing Drizzle migrations.
 * Used by scripts that generate SQL migrations (CDC setup, triggers, etc.).
 *
 * Drizzle v1 uses folder-based migrations: <timestamp>_<tag>/migration.sql
 *
 * Custom migrations are generated with 1-second delays between them to ensure
 * unique timestamps and correct ordering after Drizzle's schema migrations.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { checkMark } from '#/utils/console';

const drizzleDir = join(process.cwd(), 'drizzle');

/**
 * Warning header prepended to all generated migration SQL files.
 * Signals to LLMs and developers that the file is auto-generated.
 */
export const generatedMigrationHeader = `-- ⚠️ AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
-- This migration is generated by a script in backend/scripts/migrations/.
-- To make changes, edit the generator script and re-run it.
-- The user will handle migration generation and application.
--
`;

interface MigrationResult {
  folderName: string;
  path: string;
  tag: string;
  updated: boolean;
}

/**
 * Generate a timestamp in Drizzle v1 format (YYYYMMDDHHmmss).
 */
function generateTimestamp(): string {
  const now = new Date();
  return now.toISOString().replace(/[-:T]/g, '').slice(0, 14);
}

/**
 * Get all migration folders sorted by timestamp.
 */
export function getMigrationFolders(): string[] {
  if (!existsSync(drizzleDir)) return [];
  return readdirSync(drizzleDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && /^\d{14}_/.test(entry.name))
    .map((entry) => entry.name)
    .sort();
}

/**
 * Find a migration folder by tag suffix.
 * @param tagSuffix - The tag suffix to search for (e.g., 'cdc_setup')
 */
export function findMigrationByTag(tagSuffix: string): string | undefined {
  return getMigrationFolders().find((folder) => folder.endsWith(`_${tagSuffix}`));
}

/**
 * Get the latest snapshot from existing migrations.
 */
export function getLatestSnapshot(): object | null {
  const folders = getMigrationFolders();
  for (let i = folders.length - 1; i >= 0; i--) {
    const snapshotPath = join(drizzleDir, folders[i], 'snapshot.json');
    if (existsSync(snapshotPath)) {
      return JSON.parse(readFileSync(snapshotPath, 'utf-8'));
    }
  }
  return null;
}

/**
 * Resolve SQL content from either a file path or inline SQL string.
 * @param sqlOrPath - SQL content or path to a .sql file
 */
export function resolveSqlContent(sqlOrPath: string): string {
  const possiblePath = resolve(sqlOrPath);
  if (existsSync(possiblePath) && possiblePath.endsWith('.sql')) {
    return readFileSync(possiblePath, 'utf-8');
  }
  return sqlOrPath;
}

/**
 * Add or update a SQL migration in the Drizzle migrations folder (v1 format).
 *
 * @param tag - Unique identifier for the migration (e.g., 'cdc_setup')
 * @param sql - SQL content (not a file path - use resolveSqlContent first if needed)
 * @returns Object containing the folder name, path, tag, and whether it was an update
 */
export function upsertMigration(tag: string, sql: string): MigrationResult {
  // Normalize tag (remove leading timestamps/underscores if present)
  const normalizedTag = tag.replace(/^\d+_/, '');

  // Prepend auto-generation warning header
  const finalSql = generatedMigrationHeader + sql;

  // Check if migration with this tag already exists
  const existingFolder = findMigrationByTag(normalizedTag);

  if (existingFolder) {
    // Update existing migration file
    const folderPath = join(drizzleDir, existingFolder);
    const migrationPath = join(folderPath, 'migration.sql');
    writeFileSync(migrationPath, finalSql);
    return { folderName: existingFolder, path: folderPath, tag: normalizedTag, updated: true };
  }

  // Create new migration folder with Drizzle v1 naming convention
  const timestamp = generateTimestamp();
  const folderName = `${timestamp}_${normalizedTag}`;
  const folderPath = join(drizzleDir, folderName);

  // Create folder and write migration file
  mkdirSync(folderPath, { recursive: true });
  writeFileSync(join(folderPath, 'migration.sql'), finalSql);

  // Copy snapshot from latest migration (manual SQL migrations don't change Drizzle schema)
  const latestSnapshot = getLatestSnapshot();
  if (latestSnapshot) {
    writeFileSync(join(folderPath, 'snapshot.json'), JSON.stringify(latestSnapshot, null, 2));
  }

  return { folderName, path: folderPath, tag: normalizedTag, updated: false };
}

/**
 * Log a migration result to the console.
 */
export function logMigrationResult(result: MigrationResult, context?: string): void {
  console.info('');
  const action = result.updated ? 'updated' : 'created';
  const contextStr = context ? ` (${context})` : '';
  console.info(`${checkMark} Migration ${action}${contextStr}: drizzle/${result.folderName}/migration.sql`);
}
