encryptionsalt: v1:OB3eX2/Cavo=:v1:zUWCmiHoqAtbw5w9:nUhV6Y7FbTkk7Ok5ad1LipqvR6L/4Q==
config:
  scaleway:projectId: 3ad2b2d5-a772-40a2-a82b-bd0cee9ebb12
  infra:dbPassword:
    secure: v1:avOl6eHscB9bS8q6:wiWmt6aiY5QT15aymC49x7s9hv/Rdet45oNbF2T4QZFuJBVBc8rt8IVocnoE5Oh0
  infra:applicationId: bfe8e160-3c14-41d6-95ba-386f7a5aeaad
  infra:operatorPrincipal: application_id:f60e5fe4-a047-4a7a-af07-7e233f536e8c
  infra:ciPolicyFingerprint: 007ada11d823
  scaleway:accessKey:
    secure: v1:ORxS0DvKUrFGxiXc:vDFeDnX9eFhtrFf7LjscTNkaR9IadOEKI7QQfVzd96RugiTg
  scaleway:secretKey:
    secure: v1:3EXIrUpXy/CMWFWB:yMe89YiCzhjKcNa10Ur7yyyXlkfSjh0EERGdkYC4z7JN85opVuDVR0FV6dQfLwGok0gJvg==
  infra:vmApplicationId: 2918501f-d970-46d1-8e73-bbe273c259c8
  infra:vmAccessKey:
    secure: v1:ww0JDbm+ETk6Nr1C:LUxgbqvpJEaw0Bixr1/jX0VQJyFDU3jaXBZEhQxZ7jO/uhiI
  infra:vmSecretKey:
    secure: v1:bmj/4nMgQCxl9qrj:sSiZLjBEd17MZkif298RYAbQ7++OF02Ljiyl40V/bp5JtM9fNC0KiCum7kqPrPS3nzVR4g==
