encryptionsalt: v1:vK1Eg3Kog40=:v1:81X7eFIjZqH+iBCW:0eGX1lPDuqjW2Q/Vm1xCeO3vTASc5w==
config:
  scaleway:projectId: e2e322db-51db-4141-8b2b-1602966a9ca0
  infra:dbPassword:
    secure: v1:WVF3Jl94QkVdfYu+:vPFvUocLllfoRM04w96YnPum4fQIDjMnCA/emG5AqMSmfKJ5MOuCdHDvXPuaNJ0X7bbtbjI154zKIsBw
  infra:cookieSecret:
    secure: v1:K45kYFROELaXp4UY:E7InbP/Nqkwob01DInWWiMRfFhoZFbne0ZvQbklpLloje1FpxGx3sOXoEpqxIzp7wTKUNlWI77muM2un
  infra:unsubscribeSecret:
    secure: v1:gmxc6EA8URcQ2mcB:LujH1rf06UZhzxFvPvE1IriXoGCR6+CjAlDCNXWP5AsJbNcQI/QaXlJ4fo23p54RHcRod02g8SFwBZ7h
  infra:cdcSecret:
    secure: v1:QruC7T1FnVmeaxTc:gCtKwGO3HpGc4dONkWZoOj/c0puaGi+Qwsk0tB5GxJ4SNYXn+9H+75Z3LBvbKl1OGtfwYVBz/emyu8i9
  infra:yjsSecret:
    secure: v1:gNZ+Y6B1eqN/Rhtc:e54ucX0wXCxEuuNZPOF0fAf7IcgkN7s72w5s8P515ifg8M3WbYgYxK75Ic3fvI1sSW6pedrTA2jDMiBR
  infra:adminEmail:
    secure: v1:in2Pzf9qRyBXpV3R:SG6ZhfLsStdfKnp4sniR6XWF8y6QE1GpHj0sznilOB8pbQ==
  infra:brevoApiKey:
    secure: v1:Dt5YIKWVopu5wMhX:TnYFzVjD1RRyLcO1+eRLlq3XYx+4b9NPqzC8Thpp2Y5jcdlYsoH3eHncT0ecW8sCV5Le5x4Y3V+VvL190IqaFn7j99E8vi44WCzgKiYykFAV0uEChNeqM1S29n57LK4l6lXTzQOd0Am9
  scaleway:accessKey:
    secure: v1:EWhdqQ1dNjLQAYAj:GyK2541oLedCdxuDmU/trkcRG7BK7mg8ns87a1q8+2l3U1Ms
  scaleway:secretKey:
    secure: v1:9PSFg+iNyZeBBmOS:+IlMuPTAk1y0MSmOi/TtLelm9NssKsh/ZJUkQwvYY8z8GoFAmH7bbuRUg0fHx6d2AJ3DHg==
  infra:applicationId: e82d42ab-d70a-40b8-96ef-92ae1c3272f3
  infra:scwAiApiKey:
    secure: v1:B9q3I8kSAIjZobJv:tIJfiJbo97XAbhv5b4hp45/qLn4gnPP8A1BH8OsrGhLADrBJ
  infra:ciPolicyFingerprint: 04ad20bf4f5d
