-- CDC (Change Data Capture) Setup Migration
-- Generated by: pnpm generate:cdc-migration
-- 
-- This migration sets up PostgreSQL logical replication for the activities CDC worker.
-- Prerequisites:
--   - PostgreSQL must be started with wal_level=logical (configured in compose.yaml)
--   - max_wal_senders and max_replication_slots must be > 0
--
-- NOTE: The replication slot is created by the CDC worker on startup, not in this migration.
-- This is because pg_create_logical_replication_slot cannot run in a transaction with writes.

-- ============================================================================
-- PUBLICATION
-- ============================================================================
-- Create a publication for the tables we want to track.
-- NOTE: The 'activities' table is intentionally excluded to prevent infinite loops.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'cella_development_cdc_pub') THEN
    CREATE PUBLICATION cella_development_cdc_pub FOR TABLE users, organizations, attachments, pages, requests, memberships;
    RAISE NOTICE 'Created publication cella_development_cdc_pub';
  ELSE
    RAISE NOTICE 'Publication cella_development_cdc_pub already exists';
  END IF;
END $$;

-- ============================================================================
-- REPLICA IDENTITY
-- ============================================================================
-- Set REPLICA IDENTITY FULL on tracked tables to get old row values on UPDATE/DELETE.
-- This is required for the CDC worker to compute changedKeys accurately.

ALTER TABLE users REPLICA IDENTITY FULL;
ALTER TABLE organizations REPLICA IDENTITY FULL;
ALTER TABLE attachments REPLICA IDENTITY FULL;
ALTER TABLE pages REPLICA IDENTITY FULL;
ALTER TABLE requests REPLICA IDENTITY FULL;
ALTER TABLE memberships REPLICA IDENTITY FULL;

-- ============================================================================
-- NOTES
-- ============================================================================
-- 
-- The replication slot 'cella_development_cdc_slot' is created automatically by the CDC worker.
--
-- To check the publication:
--   SELECT * FROM pg_publication;
--   SELECT * FROM pg_publication_tables WHERE pubname = 'cella_development_cdc_pub';
--
-- To check the replication slot (after CDC worker has started):
--   SELECT * FROM pg_replication_slots WHERE slot_name = 'cella_development_cdc_slot';
--
-- To drop the publication (if needed):
--   DROP PUBLICATION IF EXISTS cella_development_cdc_pub;
--
-- To drop the replication slot (if needed):
--   SELECT pg_drop_replication_slot('cella_development_cdc_slot');
--
-- WARNING: If the CDC worker is not running, the replication slot will accumulate
-- WAL data. Monitor with: SELECT pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn) 
-- FROM pg_replication_slots WHERE slot_name = 'cella_development_cdc_slot';
