import type { IncomingMessage } from 'node:http';
import type { Duplex } from 'node:stream';
import type { ServerType } from '@hono/node-server';
import { z } from '@hono/zod-openapi';
import { isValidEventType } from 'shared';
import { type WebSocket, WebSocketServer } from 'ws';
import { env } from '#/env';
import { type ActivityEvent, activityBus } from '#/lib/activity-bus';
import { entityCache, publicEntityCache } from '#/middlewares/entity-cache';
import { activityActionSchema, activitySchema } from '#/modules/activities/activities-schema';
import { logEvent } from '#/utils/logger';

/**
 * Zod schema for CDC WebSocket message payload.
 * Validates the { activity, entity, cacheToken, _trace } structure sent by CDC Worker.
 * Reuses activitySchema with stricter typing for fields that must be present in CDC context.
 */
const cdcMessageSchema = z.object({
  activity: z.object({
    ...activitySchema.shape,
    // Override nullable fields that are always present in CDC messages
    action: activityActionSchema,
    subjectId: z.string().nullable(),
    // seq: entity-type sequence stamped by CDC worker (product entities only)
    seq: z.number().optional(),
    // Batch fields (set by CDC Worker for multi-entity transactions)
    batchUntilSeq: z.number().optional(),
    deletedIds: z.array(z.string()).optional(),
  }),
  rowData: z.record(z.string(), z.unknown()),
  // Cache token generated by CDC for realtime entities (batch token for batches)
  cacheToken: z.string().nullable(),
  // Batch cache reservations: individual entity tokens for backend entity cache
  batchReservations: z
    .array(
      z.object({
        token: z.string(),
        entityType: z.string(),
        entityId: z.string(),
      }),
    )
    .optional(),
  _trace: z
    .object({
      traceId: z.string(),
      spanId: z.string(),
      cdcTimestamp: z.number(),
      lsn: z.string().optional(),
    })
    .optional(),
});

/** Idle timeout in ms - close connection if no message received within this time */
const IDLE_TIMEOUT_MS = 90_000;

/** Ping interval in ms */
const PING_INTERVAL_MS = 30_000;

/**
 * CDC WebSocket Server — INTERNAL SERVICE ONLY.
 *
 * Accepts connections exclusively from the co-located CDC Worker process.
 * This is a server-to-server channel (Node.js → Node.js) that carries full
 * entity row data for the real-time sync pipeline. It must NEVER be exposed
 * to external networks or browser clients.
 *
 * Security layers:
 * - Path-locked to `/internal/cdc` (all other paths → 404)
 * - Shared secret via `x-cdc-secret` header (min 16 chars, validated at startup)
 * - Loopback-only in production (rejects non-localhost connections)
 * - Single connection at a time (new connections replace existing ones)
 * - Idle timeout (90s) auto-closes stale connections
 */
class CdcWebSocketServer {
  private wss: WebSocketServer | null = null;
  private currentConnection: WebSocket | null = null;
  private idleTimer: NodeJS.Timeout | null = null;
  private pingInterval: NodeJS.Timeout | null = null;

  // Health metrics
  private _cdcConnected = false;
  private _lastMessageAt: Date | null = null;
  private _messagesReceived = 0;
  private _parseErrors = 0;

  /**
   * Attach WebSocket server to an existing HTTP server.
   * Handles upgrade requests to /internal/cdc with auth validation.
   */
  attachToServer(server: ServerType): void {
    this.wss = new WebSocketServer({ noServer: true });

    // Type assertion needed because ServerType is broader than HTTP1 Server
    (server as NodeJS.EventEmitter).on('upgrade', (request: IncomingMessage, socket: Duplex, head: Buffer) => {
      // Only handle /internal/cdc path
      const url = new URL(request.url ?? '', `http://${request.headers.host}`);
      if (url.pathname !== '/internal/cdc') {
        socket.write('HTTP/1.1 404 Not Found\r\n\r\n');
        socket.destroy();
        return;
      }

      // In production, reject connections from non-loopback addresses.
      // CDC Worker must be co-located (same host / same pod).
      const remoteIp = request.socket.remoteAddress;
      if (
        env.NODE_ENV === 'production' &&
        remoteIp !== '127.0.0.1' &&
        remoteIp !== '::1' &&
        remoteIp !== '::ffff:127.0.0.1'
      ) {
        logEvent(null, 'warn', 'CDC WebSocket rejected non-loopback connection', { ip: remoteIp });
        socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');
        socket.destroy();
        return;
      }

      // Validate shared secret — always required
      const secret = request.headers['x-cdc-secret'];
      if (!env.CDC_SECRET || secret !== env.CDC_SECRET) {
        logEvent(null, 'warn', 'CDC WebSocket auth failed', {
          ip: request.socket.remoteAddress,
          reason: !env.CDC_SECRET ? 'CDC_SECRET not configured' : 'invalid secret',
        });
        socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');
        socket.destroy();
        return;
      }

      this.wss?.handleUpgrade(request, socket, head, (ws) => {
        this.handleConnection(ws);
      });
    });

    logEvent(null, 'info', 'CDC WebSocket server attached to HTTP server');
  }

  /**
   * Handle a new WebSocket connection from CDC Worker.
   * Replaces existing connection if one exists.
   */
  private handleConnection(ws: WebSocket): void {
    // Close existing connection if any (graceful replacement)
    if (this.currentConnection) {
      logEvent(null, 'info', 'Replacing existing CDC Worker connection');
      this.currentConnection.close(1000, 'Replaced by new connection');
    }

    this.currentConnection = ws;
    this._cdcConnected = true;
    this.resetIdleTimer();
    this.startPingInterval();

    logEvent(null, 'info', 'CDC Worker connected via WebSocket');

    ws.on('message', (data) => {
      this.resetIdleTimer();
      this.handleMessage(data.toString());
    });

    ws.on('pong', () => {
      this.resetIdleTimer();
    });

    ws.on('close', (code, reason) => {
      logEvent(null, 'info', 'CDC Worker disconnected', { code, reason: reason.toString() });
      this.cleanup();
    });

    ws.on('error', (err) => {
      logEvent(null, 'error', 'CDC WebSocket error', { error: err.message });
      this.cleanup();
    });
  }

  /**
   * Handle incoming message from CDC Worker.
   * Validates JSON schema and transforms message into ActivityBus event.
   */
  private handleMessage(data: string): void {
    try {
      const parsed = JSON.parse(data);

      // Handle CDC control messages (e.g. catchup_complete) before schema validation
      if (parsed?._control) {
        this.handleControlMessage(parsed);
        return;
      }

      const result = cdcMessageSchema.safeParse(parsed);

      if (!result.success) {
        this._parseErrors++;
        // Extract what we can from the raw message for debugging
        const preview = {
          type: parsed?.activity?.type,
          subjectId: parsed?.activity?.subjectId,
          action: parsed?.activity?.action,
        };
        logEvent(null, 'error', 'CDC message schema validation failed - message dropped', {
          errors: result.error.issues,
          preview,
        });
        return;
      }

      const message = result.data;
      this._messagesReceived++;
      this._lastMessageAt = new Date();

      // Validate event type is a known ActivityEventType
      const { type } = message.activity;
      if (!isValidEventType(type)) {
        this._parseErrors++;
        logEvent(null, 'error', 'Unknown event type in CDC message - message dropped', {
          type,
          subjectId: message.activity.subjectId,
        });
        return;
      }

      // Process batch cache reservations if present
      if (message.batchReservations?.length && message.cacheToken) {
        const entityKeys: string[] = [];
        for (const reservation of message.batchReservations) {
          const entityKey = `${reservation.entityType}:${reservation.entityId}`;
          entityCache.reserve(reservation.token, reservation.entityType, reservation.entityId);
          entityKeys.push(entityKey);
        }
        entityCache.reserveBatch(message.cacheToken, entityKeys);
      } else if (message.cacheToken && message.activity.entityType && message.activity.subjectId) {
        // Single entity: reserve cache token as before
        entityCache.reserve(message.cacheToken, message.activity.entityType, message.activity.subjectId);
      }

      // Transform CDC message to ActivityBus event and emit
      const activityEvent = {
        ...message.activity,
        type,
        rowData: message.rowData,
        seq: message.activity.seq ?? null,
        cacheToken: message.cacheToken,
        batchUntilSeq: message.activity.batchUntilSeq ?? null,
        deletedIds: message.activity.deletedIds ?? null,
        propagation: null,
        trace: message._trace ?? null,
      } as ActivityEvent;

      logEvent(null, 'trace', 'CDC message processed', {
        type: message.activity.type,
        subjectId: message.activity.subjectId,
      });

      activityBus.emit(activityEvent);
    } catch (err) {
      this._parseErrors++;
      logEvent(null, 'error', 'Failed to parse CDC message', { error: err });
    }
  }

  /**
   * Handle CDC control messages (not regular activity events).
   * These are sent by the CDC worker to signal lifecycle events like catchup completion.
   */
  private handleControlMessage(message: { _control: string; [key: string]: unknown }): void {
    if (message._control === 'catchup_complete') {
      const eventsProcessed = message.eventsProcessed ?? 0;
      const catchupDurationMs = message.catchupDurationMs ?? 0;

      // Clear all entity caches — counters were recalculated, data may be stale
      entityCache.clear();
      publicEntityCache.clear();

      logEvent(null, 'info', 'CDC catchup complete — entity caches cleared', {
        eventsProcessed,
        catchupDurationMs,
      });
      return;
    }

    logEvent(null, 'warn', 'Unknown CDC control message', { control: message._control });
  }

  /**
   * Reset idle timer - connection will be closed if no activity.
   */
  private resetIdleTimer(): void {
    if (this.idleTimer) clearTimeout(this.idleTimer);
    this.idleTimer = setTimeout(() => {
      logEvent(null, 'warn', 'CDC WebSocket idle timeout, closing connection');
      this.currentConnection?.close(1000, 'Idle timeout');
    }, IDLE_TIMEOUT_MS);
  }

  /**
   * Start sending periodic pings to keep connection alive.
   */
  private startPingInterval(): void {
    if (this.pingInterval) clearInterval(this.pingInterval);
    this.pingInterval = setInterval(() => {
      if (this.currentConnection?.readyState === 1) {
        // WebSocket.OPEN
        this.currentConnection.ping();
      }
    }, PING_INTERVAL_MS);
  }

  /**
   * Clean up connection state.
   */
  private cleanup(): void {
    if (this.idleTimer) {
      clearTimeout(this.idleTimer);
      this.idleTimer = null;
    }
    if (this.pingInterval) {
      clearInterval(this.pingInterval);
      this.pingInterval = null;
    }
    this.currentConnection = null;
    this._cdcConnected = false;
  }

  /**
   * Get health status for the CDC WebSocket connection.
   */
  getHealthStatus(): {
    cdcConnected: boolean;
    lastMessageAt: string | null;
    messagesReceived: number;
    parseErrors: number;
    status: 'healthy' | 'degraded' | 'unknown';
  } {
    // Determine status based on connection and message timing
    let status: 'healthy' | 'degraded' | 'unknown' = 'unknown';

    if (this._cdcConnected) {
      // If connected and received message recently (within 60s), healthy
      const sixtySecondsAgo = Date.now() - 60_000;
      if (this._lastMessageAt && this._lastMessageAt.getTime() > sixtySecondsAgo) {
        status = 'healthy';
      } else if (this._lastMessageAt) {
        status = 'degraded'; // Connected but no recent messages
      } else {
        status = 'healthy'; // Just connected, no messages yet is OK
      }
    } else if (env.DEV_MODE === 'full' || env.NODE_ENV === 'production') {
      // CDC expected but not connected
      status = 'degraded';
    }
    // In basic/core mode without CDC, status remains 'unknown' (not applicable)

    return {
      cdcConnected: this._cdcConnected,
      lastMessageAt: this._lastMessageAt?.toISOString() ?? null,
      messagesReceived: this._messagesReceived,
      parseErrors: this._parseErrors,
      status,
    };
  }

  /**
   * Close the WebSocket server.
   */
  close(): void {
    this.cleanup();
    this.wss?.close();
    this.wss = null;
  }
}

/** Singleton CDC WebSocket server instance */
export const cdcWebSocketServer = new CdcWebSocketServer();
