import { defineManagedKeys } from '../lib/managed-keys';

/** App-owned registry of scoped IAM keys the CLI can mint into operator runtime secrets. Every mint or rotation requires operator confirmation. */
export const managedKeysConfig = defineManagedKeys({
  ai: {
    suffix: 'ai',
    label: 'AI worker (Scaleway Generative APIs / Inference)',
    appDescription: 'AI worker principal, Scaleway Generative APIs + Inference (consumed by the MCP/AI worker)',
    policyDescription: 'AI worker policy: Generative APIs + Inference (auto-generated by infra CLI)',
    permissionSets: ['GenerativeApisFullAccess', 'GenerativeApisModelAccess', 'InferenceFullAccess'],
    // Generative APIs are billed per use, so the prompt defaults to no.
    prompt: {
      message: 'Mint a scoped Scaleway AI key now? (enables the MCP/AI worker; inference is billed)',
      default: false,
    },
    // Scaleway Generative APIs authenticate with a single Bearer token, the key's secret half.
    assign: { secretKey: 'scwAiApiKey' },
  },
});
