import { defineRuntimeSecrets } from '../lib/runtime-secrets'

/**
 * Fork-owned mapping from runtime secrets to their consuming services.
 * Per-service manifests restrict each VM to the values it needs; `runtime-secrets.ts`
 * provisions containers and validates the registry. The file is pinned so forks can
 * customize distribution without upstream sync conflicts.
 */
export const runtimeSecretsConfig = defineRuntimeSecrets({
  databaseUrlRuntime: {
    secretName: 'database-url-runtime',
    description: 'PostgreSQL runtime_role connection string (backend API, subject to RLS)',
    envVar: 'DATABASE_URL',
    required: true,
    valueSource: 'pulumi',
    generation: 'manual',
    services: ['backend', 'yjs', 'mcp'],
  },
  databaseUrlAdmin: {
    secretName: 'database-url-admin',
    description: 'PostgreSQL admin_role connection string (migrations, seeds, BYPASSRLS)',
    envVar: 'DATABASE_ADMIN_URL',
    required: true,
    valueSource: 'pulumi',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  databaseUrlCdc: {
    secretName: 'database-url-cdc',
    description: 'PostgreSQL CDC worker connection string (admin_role with replication access)',
    envVar: 'DATABASE_CDC_URL',
    required: true,
    valueSource: 'pulumi',
    generation: 'manual',
    services: ['cdc'],
  },
  databaseSslCa: {
    secretName: 'database-ssl-ca',
    description:
      'base64-encoded PEM CA cert of the Scaleway RDB instance, used by services to verify the PostgreSQL TLS connection (derived by pulumi from the database instance; base64 keeps the multi-line PEM deliverable through the line-based .env.runtime)',
    envVar: 'DATABASE_SSL_CA',
    required: true,
    valueSource: 'pulumi',
    generation: 'manual',
    services: ['backend', 'yjs', 'mcp', 'cdc'],
  },
  cookieSecret: {
    secretName: 'cookie-secret',
    description: 'Cookie signing secret',
    envVar: 'COOKIE_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  unsubscribeSecret: {
    secretName: 'unsubscribe-token-secret',
    description: 'Email unsubscribe token secret',
    envVar: 'UNSUBSCRIBE_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  cdcSecret: {
    secretName: 'cdc-secret',
    description: 'CDC authentication secret',
    envVar: 'CDC_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'cdc', 'mcp'],
  },
  yjsSecret: {
    secretName: 'yjs-secret',
    description: 'Yjs WebSocket authentication secret',
    envVar: 'YJS_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'yjs', 'mcp'],
  },
  piiHashSecret: {
    secretName: 'pii-hash-secret',
    description: 'HMAC pepper for hashing PII-derived identifiers',
    envVar: 'PII_HASH_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  dataEncryptionKey: {
    secretName: 'data-encryption-key',
    description: 'Root key for reversible encryption of sensitive database fields',
    envVar: 'DATA_ENCRYPTION_KEY',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  adminEmail: {
    secretName: 'admin-email',
    description: 'Primary administrative contact email',
    envVar: 'ADMIN_EMAIL',
    required: true,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  brevoApiKey: {
    secretName: 'brevo-api-key',
    description: 'Brevo transactional email API key',
    envVar: 'BREVO_API_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  scwAiApiKey: {
    secretName: 'scw-ai-api-key',
    description: 'Scaleway AI API key for the MCP worker',
    envVar: 'SCW_AI_API_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  mapleSecretIngestKey: {
    secretName: 'maple-secret-ingest-key',
    description: 'Maple.dev observability secret ingest key (server-side traces, metrics, logs)',
    envVar: 'MAPLE_SECRET_INGEST_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'cdc', 'yjs'],
  },
  githubClientId: {
    secretName: 'github-client-id',
    description: 'GitHub OAuth client ID',
    envVar: 'GITHUB_CLIENT_ID',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  githubClientSecret: {
    secretName: 'github-client-secret',
    description: 'GitHub OAuth client secret',
    envVar: 'GITHUB_CLIENT_SECRET',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  systemAdminIpAllowlist: {
    secretName: 'system-admin-ip-allowlist',
    description: "System admin IP allowlist ('none' to disable, '*' for any IP, or comma-separated IPv4 addresses)",
    envVar: 'SYSTEM_ADMIN_IP_ALLOWLIST',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  // The S3 pair shares one scoped key and keeps its empty containers Pulumi-owned.
  // It is backend-only because attachment signing and upload are API concerns.
  s3AccessKeyId: {
    secretName: 's3-access-key-id',
    description: 'Scaleway Object Storage access key id (attachment upload + presigned URLs)',
    envVar: 'S3_ACCESS_KEY_ID',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend'],
  },
  s3AccessKeySecret: {
    secretName: 's3-access-key-secret',
    description: 'Scaleway Object Storage secret key (attachment upload + presigned URLs)',
    envVar: 'S3_ACCESS_KEY_SECRET',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend'],
  },
});
