import { defineRuntimeSecrets } from '../lib/runtime-secrets';

/**
 * App-owned mapping from runtime secrets to their consuming services; per-service manifests restrict each VM to the values it needs.
 * Database DSN and CA secrets are declared by the primary store in config/stores.config.ts and merge ahead of these entries.
 */
export const runtimeSecretsConfig = defineRuntimeSecrets({
  cookieSecret: {
    secretName: 'cookie-secret',
    description: 'Cookie signing secret',
    envVar: 'COOKIE_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  unsubscribeSecret: {
    secretName: 'unsubscribe-token-secret',
    description: 'Email unsubscribe token secret',
    envVar: 'UNSUBSCRIBE_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  cdcSecret: {
    secretName: 'cdc-secret',
    description: 'CDC authentication secret',
    envVar: 'CDC_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'cdc', 'mcp'],
  },
  yjsSecret: {
    secretName: 'yjs-secret',
    description: 'Yjs WebSocket authentication secret',
    envVar: 'YJS_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'yjs', 'mcp'],
  },
  piiHashSecret: {
    secretName: 'pii-hash-secret',
    description: 'HMAC pepper for hashing PII-derived identifiers',
    envVar: 'PII_HASH_SECRET',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  dataEncryptionKey: {
    secretName: 'data-encryption-key',
    description: 'Root key for reversible encryption of sensitive database fields',
    envVar: 'DATA_ENCRYPTION_KEY',
    required: true,
    valueSource: 'pulumi',
    generation: 'random',
    services: ['backend', 'mcp'],
  },
  adminEmail: {
    secretName: 'admin-email',
    description: 'Primary administrative contact email',
    envVar: 'ADMIN_EMAIL',
    required: true,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  brevoApiKey: {
    secretName: 'brevo-api-key',
    description: 'Brevo transactional email API key',
    envVar: 'BREVO_API_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  scwAiApiKey: {
    secretName: 'scw-ai-api-key',
    description: 'Scaleway AI API key for the MCP worker',
    envVar: 'SCW_AI_API_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  mapleSecretIngestKey: {
    secretName: 'maple-secret-ingest-key',
    description: 'Maple.dev observability secret ingest key (server-side traces, metrics, logs)',
    envVar: 'MAPLE_SECRET_INGEST_KEY',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'cdc', 'yjs'],
  },
  githubClientId: {
    secretName: 'github-client-id',
    description: 'GitHub OAuth client ID',
    envVar: 'GITHUB_CLIENT_ID',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  githubClientSecret: {
    secretName: 'github-client-secret',
    description: 'GitHub OAuth client secret',
    envVar: 'GITHUB_CLIENT_SECRET',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
  systemAdminIpAllowlist: {
    secretName: 'system-admin-ip-allowlist',
    description: "System admin IP allowlist ('none' to disable, '*' for any IP, or comma-separated IPv4 addresses)",
    envVar: 'SYSTEM_ADMIN_IP_ALLOWLIST',
    required: false,
    valueSource: 'operator',
    generation: 'manual',
    services: ['backend', 'mcp'],
  },
});
