import type { HttpErrorStatus } from '#/lib/errors';

export const errorDescriptions: Record<HttpErrorStatus, string> = {
  400: 'Bad request: problem processing request.',
  401: 'Unauthorized: authentication required.',
  402: 'Payment required: payment is needed to proceed.',
  403: 'Forbidden: insufficient permissions.',
  404: 'Not found: resource does not exist.',
  405: 'Method Not Allowed: the request method is not supported for the resource.',
  406: 'Not Acceptable: the resource is not capable of generating content according to the Accept headers.',
  407: 'Proxy Authentication Required: authentication is required for the proxy.',
  408: 'Request Timeout: the server timed out waiting for the request.',
  409: 'Conflict: request could not be completed due to a conflict.',
  410: 'Gone: resource is no longer available and will not be available again.',
  411: 'Length Required: server requires Content-Length header.',
  412: 'Precondition Failed: a precondition in the request headers was false.',
  413: 'Payload Too Large: the request entity is larger than the server is willing to process.',
  414: 'URI Too Long: the URI requested is too long for the server to process.',
  415: 'Unsupported Media Type: the media format of the requested data is not supported by the server.',
  416: 'Range Not Satisfiable: the range specified in the request cannot be fulfilled.',
  417: 'Expectation Failed: the server cannot meet the requirements of the Expect header.',
  418: "I'm a teapot: the server is a teapot and cannot brew coffee (an April Fools joke).",
  421: 'Misdirected Request: the request was directed at a server that is not able to produce a response.',
  422: 'Unprocessable Entity: the request was well-formed, but the server could not process the contained instructions.',
  423: 'Locked: the resource is locked and cannot be modified.',
  424: 'Failed Dependency: the request failed because of a previous request.',
  425: 'Too Early: the server is unwilling to risk processing a request that might be replayed.',
  426: 'Upgrade Required: the client should switch to a different protocol.',
  428: 'Precondition Required: the server requires certain conditions before processing the request.',
  429: 'Too Many Requests: the user has sent too many requests in a given amount of time.',
  431: 'Request Header Fields Too Large: the server is refusing to process a request because the header fields are too large.',
  451: 'Unavailable For Legal Reasons: the server is refusing to fulfill the request due to legal reasons.',
  500: 'Internal Server Error: generic error when the server fails to fulfill the request.',
  501: 'Not Implemented: the server does not support the functionality required to fulfill the request.',
  502: 'Bad Gateway: the server received an invalid response from the upstream server.',
  503: 'Service Unavailable: the server is temporarily unable to handle the request due to a temporary overload or maintenance.',
  504: 'Gateway Timeout: the server did not receive a timely response from the upstream server.',
  505: 'HTTP Version Not Supported: the server does not support the HTTP protocol version that was used.',
  506: 'Variant Also Negotiates: the server has an internal configuration error that prevents it from fulfilling the request.',
  507: 'Insufficient Storage: the server is unable to store the representation needed to complete the request.',
  508: 'Loop Detected: the server detected an infinite loop while processing the request.',
  510: 'Not Extended: further extensions to the request are required for the server to fulfill it.',
  511: 'Network Authentication Required: the client needs to authenticate to gain network access.',
};
