import { nanoid } from 'shared/nanoid';
import type { z } from 'zod';
import { useUserStore } from '~/store/user';

/**
 * Zod v4 schema definition structure (internal API).
 * Using 'any' for the internal _def since Zod v4 doesn't export these types.
 */
// biome-ignore lint/suspicious/noExplicitAny: Zod v4 internal API not exported
type ZodDef = any;

/**
 * Extract a sensible default value from a Zod v4 schema field.
 * Traverses the schema definition to determine the appropriate empty/default value.
 */
const getDefaultForZodType = (schema: { _def: ZodDef }): unknown => {
  const def = schema._def;
  const type = def.type;

  switch (type) {
    case 'string':
      return '';

    case 'number':
    case 'bigint':
      return 0;

    case 'boolean':
      return false;

    case 'date':
      return new Date().toISOString();

    case 'null':
      return null;

    case 'undefined':
      return undefined;

    case 'array':
      return [];

    case 'object': {
      // Recursively build object defaults
      const shape = def.shape ?? {};
      const result: Record<string, unknown> = {};
      for (const [key, value] of Object.entries(shape)) {
        result[key] = getDefaultForZodType(value as { _def: ZodDef });
      }
      return result;
    }

    case 'enum':
      // Return first enum value as default
      return def.entries ? Object.values(def.entries)[0] : '';

    case 'literal':
      return def.value;

    case 'union': {
      // For unions, try to find null first (common pattern: z.union([z.string(), z.null()]))
      const options = def.options ?? [];
      for (const option of options) {
        if (option._def?.type === 'null' || option.type === 'null') {
          return null;
        }
      }
      // Otherwise use first option
      return options.length > 0 ? getDefaultForZodType(options[0]) : null;
    }

    case 'optional':
    case 'nullable':
      // For optional/nullable, try the inner type but fallback to null/undefined
      return def.innerType ? getDefaultForZodType(def.innerType) : null;

    case 'default':
      // Use the schema's own default
      return typeof def.defaultValue === 'function' ? def.defaultValue() : def.defaultValue;

    case 'record':
      return {};

    case 'map':
      return new Map();

    case 'set':
      return new Set();

    case 'tuple':
      // Return defaults for each tuple element
      return (def.items ?? []).map((item: { _def: ZodDef }) => getDefaultForZodType(item));

    case 'any':
    case 'unknown':
      return null;

    default:
      console.debug(`[createOptimisticEntity] Unhandled Zod type: ${type}`);
      return null;
  }
};

/**
 * Generate default values for all fields in a Zod object schema.
 * Returns a complete object with sensible defaults for each field.
 */
export const getSchemaDefaults = <T extends z.ZodObject<z.ZodRawShape>>(schema: T): z.infer<T> => {
  const shape = schema._def.shape ?? {};
  const result: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(shape)) {
    result[key] = getDefaultForZodType(value as unknown as { _def: ZodDef });
  }

  return result as z.infer<T>;
};

/**
 * Fields that are auto-generated for optimistic entities.
 */
type AutoGeneratedFields = 'id' | 'createdAt' | 'createdBy' | 'modifiedAt' | 'modifiedBy';

/**
 * Create an optimistic entity from a Zod schema and partial input.
 *
 * This utility generates a complete entity object suitable for optimistic updates by:
 * 1. Extracting default values from the Zod schema (no hardcoded defaults needed)
 * 2. Overlaying user-provided input
 * 3. Auto-generating optimistic fields (temp id, timestamps, user refs)
 *
 * @param schema - The Zod object schema (e.g., zPage from api.gen)
 * @param input - Partial input from the create mutation (e.g., { name: 'My Page' })
 * @returns A complete entity object ready for optimistic cache insertion
 *
 * @example
 * ```ts
 * import { zPage } from '~/api.gen/zod.gen';
 * const optimisticPage = createOptimisticEntity(zPage, { name: 'New Page' });
 * ```
 */
export const createOptimisticEntity = <T extends z.ZodObject<z.ZodRawShape>>(
  schema: T,
  input: Partial<Omit<z.infer<T>, AutoGeneratedFields>> & { id?: string } = {},
): z.infer<T> => {
  const user = useUserStore.getState().user;
  const createdByUser = user
    ? {
        id: user.id,
        name: user.name,
        slug: user.slug,
        thumbnailUrl: user.thumbnailUrl,
        email: user.email,
        entityType: 'user' as const,
      }
    : null;

  // Get defaults from schema
  const defaults = getSchemaDefaults(schema);

  // Merge: schema defaults < user input < auto-generated fields
  return {
    ...defaults,
    ...input,
    id: input.id || nanoid(),
    createdAt: new Date().toISOString(),
    createdBy: createdByUser,
    modifiedAt: null,
    modifiedBy: null,
    _optimistic: true,
  } as z.infer<T>;
};

/**
 * Type helper to extract the entity type from a Zod schema.
 */
export type EntityFromSchema<T extends z.ZodTypeAny> = z.infer<T>;
