-- ⚠️ AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
-- This migration is generated by a script in backend/scripts/migrations/.
-- To make changes, edit the generator script and re-run it.
-- The user will handle migration generation and application.
--
-- Combined side-effect migration.
-- Blocks (in order): cdc_setup, counter_functions, immutability_setup, partman_setup, rls_setup, unlogged_setup
-- Regenerate with `pnpm generate`. Every block is idempotent; the whole set re-runs
-- whenever ANY block changes, so this file always reflects the full current side-effect state.

-- ══════════════════════════════════════════════════════════════════════════
-- [cdc_setup] CDC — publication, replica identity, replication slot
-- ══════════════════════════════════════════════════════════════════════════
-- CDC (Change Data Capture) Setup
-- Sets up PostgreSQL logical replication for the activities CDC worker.
-- Requires: wal_level=logical (see compose.yaml)
-- Gracefully skips if logical replication is not available.

DO $$
BEGIN
  -- Check if pg_publication is available
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class WHERE relname = 'pg_publication') THEN
    RAISE NOTICE 'Logical replication not available - skipping CDC setup.';
    RETURN;
  END IF;

  -- 1. Create or update publication
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'cdc_pub') THEN
      CREATE PUBLICATION cdc_pub FOR TABLE users, organizations, attachments, requests, memberships, inactive_memberships, tenants;
      RAISE NOTICE 'Created publication cdc_pub';
    ELSE
      -- Publication exists — replace with current table list
      RAISE NOTICE 'Publication cdc_pub already exists, syncing tables...';
      ALTER PUBLICATION cdc_pub SET TABLE users, organizations, attachments, requests, memberships, inactive_memberships, tenants;
      RAISE NOTICE 'Publication tables synced';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Publication setup failed: % (SQLSTATE: %)', SQLERRM, SQLSTATE;
  END;

  -- 2. Set REPLICA IDENTITY FULL (separate block)
  BEGIN
    ALTER TABLE users REPLICA IDENTITY FULL;
    ALTER TABLE organizations REPLICA IDENTITY FULL;
    ALTER TABLE attachments REPLICA IDENTITY FULL;
    ALTER TABLE requests REPLICA IDENTITY FULL;
    ALTER TABLE memberships REPLICA IDENTITY FULL;
    ALTER TABLE inactive_memberships REPLICA IDENTITY FULL;
    ALTER TABLE tenants REPLICA IDENTITY FULL;
    RAISE NOTICE 'REPLICA IDENTITY FULL set on all tracked tables';
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'REPLICA IDENTITY setup failed: % (SQLSTATE: %)', SQLERRM, SQLSTATE;
  END;

  -- 3. Create replication slot (separate block - may fail on managed providers)
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name = 'cdc_slot') THEN
      PERFORM pg_create_logical_replication_slot('cdc_slot', 'pgoutput');
      RAISE NOTICE 'Created replication slot cdc_slot';
    ELSE
      RAISE NOTICE 'Replication slot cdc_slot already exists';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Replication slot setup failed: % (SQLSTATE: %). Worker will create it at startup.', SQLERRM, SQLSTATE;
  END;

  RAISE NOTICE 'CDC setup complete.';
END $$;
--> statement-breakpoint
-- ══════════════════════════════════════════════════════════════════════════
-- [counter_functions] Counter functions — apply_count_deltas
-- ══════════════════════════════════════════════════════════════════════════
-- Counter Functions Setup
-- PL/pgSQL helper for JSONB counter delta merging.
-- Used by the CDC worker for prepared-statement-compatible counter upserts.

CREATE OR REPLACE FUNCTION apply_count_deltas(existing jsonb, deltas jsonb)
RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE
AS $$
DECLARE
  result jsonb := COALESCE(existing, '{}'::jsonb);
  k text;
  v text;
BEGIN
  FOR k, v IN SELECT * FROM jsonb_each_text(deltas)
  LOOP
    IF k LIKE 'li:%' OR k LIKE 'lu:%' THEN
      -- Activity stamps (epoch ms): keep the max, the signal only moves forward
      result := result || jsonb_build_object(
        k, GREATEST(COALESCE((result->>k)::bigint, 0), v::bigint)
      );
    ELSE
      result := result || jsonb_build_object(
        k, GREATEST(0, COALESCE((result->>k)::bigint, 0) + v::bigint)
      );
    END IF;
  END LOOP;
  RETURN result;
END;
$$;
--> statement-breakpoint
-- ══════════════════════════════════════════════════════════════════════════
-- [immutability_setup] Immutability triggers — identity columns, write guards
-- ══════════════════════════════════════════════════════════════════════════
-- Immutability Triggers Setup
-- Prevents modification of identity columns after row creation.
-- Gracefully skips triggers if required roles are not yet created.

-- Functions are always created (harmless without triggers)

CREATE OR REPLACE FUNCTION base_entity_immutable_keys() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.entity_type IS DISTINCT FROM OLD.entity_type
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.created_by IS DISTINCT FROM OLD.created_by THEN
    RAISE EXCEPTION 'Cannot modify immutable columns (%) on %', 'id, tenant_id, entity_type, created_at, created_by', TG_TABLE_NAME;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION product_entity_immutable_keys() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.entity_type IS DISTINCT FROM OLD.entity_type
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.created_by IS DISTINCT FROM OLD.created_by
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
    RAISE EXCEPTION 'Cannot modify immutable columns (%) on %', 'id, tenant_id, entity_type, created_at, created_by, organization_id', TG_TABLE_NAME;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION membership_immutable_keys() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.channel_id IS DISTINCT FROM OLD.channel_id
       OR NEW.channel_type IS DISTINCT FROM OLD.channel_type
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id
       OR NEW.user_id IS DISTINCT FROM OLD.user_id THEN
    RAISE EXCEPTION 'Cannot modify immutable columns (%) on %', 'tenant_id, channel_id, channel_type, organization_id, user_id', TG_TABLE_NAME;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION inactive_membership_immutable_keys() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
       OR NEW.channel_id IS DISTINCT FROM OLD.channel_id
       OR NEW.channel_type IS DISTINCT FROM OLD.channel_type
       OR NEW.organization_id IS DISTINCT FROM OLD.organization_id THEN
    RAISE EXCEPTION 'Cannot modify immutable columns (%) on %', 'tenant_id, channel_id, channel_type, organization_id', TG_TABLE_NAME;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION append_only_immutable_row() RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Table % is append-only: updates are not allowed', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

CREATE OR REPLACE FUNCTION admin_only_write_row() RETURNS TRIGGER AS $$
BEGIN
  IF current_user = 'runtime_role' THEN
    RAISE EXCEPTION 'Table % is not writable by %', TG_TABLE_NAME, current_user;
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint

-- Triggers require roles to exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'runtime_role') THEN
    RAISE NOTICE 'Roles not available - skipping immutability triggers.';
    RETURN;
  END IF;

  BEGIN
    EXECUTE 'DROP TRIGGER IF EXISTS organizations_immutable_keys_trigger ON organizations';
    EXECUTE 'CREATE TRIGGER organizations_immutable_keys_trigger BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION base_entity_immutable_keys()';
    EXECUTE 'DROP TRIGGER IF EXISTS attachments_immutable_keys_trigger ON attachments';
    EXECUTE 'CREATE TRIGGER attachments_immutable_keys_trigger BEFORE UPDATE ON attachments FOR EACH ROW EXECUTE FUNCTION product_entity_immutable_keys()';
    EXECUTE 'DROP TRIGGER IF EXISTS memberships_immutable_keys_trigger ON memberships';
    EXECUTE 'CREATE TRIGGER memberships_immutable_keys_trigger BEFORE UPDATE ON memberships FOR EACH ROW EXECUTE FUNCTION membership_immutable_keys()';
    EXECUTE 'DROP TRIGGER IF EXISTS inactive_memberships_immutable_keys_trigger ON inactive_memberships';
    EXECUTE 'CREATE TRIGGER inactive_memberships_immutable_keys_trigger BEFORE UPDATE ON inactive_memberships FOR EACH ROW EXECUTE FUNCTION inactive_membership_immutable_keys()';
    EXECUTE 'DROP TRIGGER IF EXISTS activities_immutable_keys_trigger ON activities';
    EXECUTE 'CREATE TRIGGER activities_immutable_keys_trigger BEFORE UPDATE ON activities FOR EACH ROW EXECUTE FUNCTION append_only_immutable_row()';
    EXECUTE 'DROP TRIGGER IF EXISTS system_roles_admin_only_write_trigger ON system_roles';
    EXECUTE 'CREATE TRIGGER system_roles_admin_only_write_trigger BEFORE INSERT OR UPDATE OR DELETE ON system_roles FOR EACH ROW EXECUTE FUNCTION admin_only_write_row()';

    RAISE NOTICE 'Immutability triggers setup complete.';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Immutability triggers setup failed: %. Skipping.', SQLERRM;
  END;
END $$;
--> statement-breakpoint
-- ══════════════════════════════════════════════════════════════════════════
-- [partman_setup] pg_partman — partitioned tables
-- ══════════════════════════════════════════════════════════════════════════
-- =============================================================================
-- Migration: pg_partman Setup for Token/Session/Activity/SeenBy Tables
-- =============================================================================
-- This migration converts sessions, tokens, unsubscribe_tokens, activities,
-- and seen_by to partitioned tables managed by pg_partman for automatic cleanup.
--
-- IMPORTANT: This creates a schema drift between Drizzle and the actual DB:
-- - Drizzle sees: regular tables with composite PKs
-- - PostgreSQL has: partitioned tables with composite PKs
--
-- This is intentional. Standard ALTER TABLE operations (ADD COLUMN, etc.)
-- work fine on partitioned tables. Only avoid operations that recreate tables.
--
-- Tables affected:
-- - sessions: partitioned by expires_at (weekly, 30-day retention)
-- - tokens: partitioned by expires_at (weekly, 30-day retention)
-- - unsubscribe_tokens: partitioned by created_at (monthly, 90-day retention)
-- - activities: partitioned by created_at (weekly, 90-day retention)
-- - seen_by: partitioned by created_at (weekly, 90-day retention)
--
-- pg_partman is required to reap these tables. If it is not available the
-- migration is skipped and the tables grow unbounded — local dev installs the
-- extension via backend/db/Dockerfile; production managed Postgres has it enabled.
-- =============================================================================

-- First check: Skip entirely if extensions are not supported
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_extension WHERE extname = 'plpgsql') THEN
    RAISE NOTICE 'Extensions not available - skipping partman setup.';
    RETURN;
  END IF;
END $$;--> statement-breakpoint

-- Second phase: Check if pg_partman is available and run setup
DO $$
DECLARE
  partman_available BOOLEAN := false;
  r RECORD;
  cols_new text;
  cols_old text;
BEGIN
  -- Try to create pg_partman extension
  BEGIN
    CREATE SCHEMA IF NOT EXISTS partman;
    CREATE EXTENSION IF NOT EXISTS pg_partman SCHEMA partman;
    partman_available := true;
    RAISE NOTICE 'pg_partman extension enabled';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pg_partman not available - skipping partition setup. Manual cleanup will be used.';
    RETURN;
  END;

  IF NOT partman_available THEN
    RETURN;
  END IF;

  -- Wrap all partition conversions in an exception handler so environments
  -- where pg_partman installs but partitioning operations fail (e.g., Neon)
  -- still complete the migration successfully.
  BEGIN

  -- ==========================================================================
  -- SESSIONS TABLE: Convert to partitioned
  -- ==========================================================================

  -- Skip if already partitioned
  IF EXISTS (
    SELECT 1 FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'sessions' AND c.relnamespace = 'public'::regnamespace
  ) THEN
    -- Update retention config in case it changed
    UPDATE partman.part_config SET
      retention = '30 days',
      retention_keep_table = false,
      infinite_time_partitions = true
    WHERE parent_table = 'public.sessions';
    RAISE NOTICE 'sessions already partitioned — config updated, skipping conversion';
  ELSE
  -- 1. Rename existing table
  ALTER TABLE sessions RENAME TO sessions_old;
  
  -- 2. Create partitioned table with same structure (dynamic SQL to avoid parse errors)
  EXECUTE 'CREATE TABLE sessions (
    id uuid NOT NULL,
    secret varchar(255) NOT NULL,
    type varchar NOT NULL DEFAULT ''regular'',
    user_id uuid NOT NULL,
    device_name varchar(255),
    device_type varchar NOT NULL DEFAULT ''desktop'',
    device_os varchar(255),
    browser varchar(255),
    auth_strategy varchar NOT NULL,
    ip_hash varchar(64),
    ip_subnet_hash varchar(64),
    ip_country varchar(2),
    ip_asn integer,
    device_id_hash varchar(64),
    created_at timestamp DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    CONSTRAINT sessions_id_expires_at_pk PRIMARY KEY (id, expires_at),
    CONSTRAINT sessions_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  ) PARTITION BY RANGE (expires_at)';
  
  -- 3. Create indexes
  EXECUTE 'CREATE INDEX sessions_secret_idx ON sessions (secret)';
  EXECUTE 'CREATE INDEX sessions_user_id_idx ON sessions (user_id)';
  EXECUTE 'CREATE INDEX sessions_user_id_ip_hash_idx ON sessions (user_id, ip_hash)';
  EXECUTE 'CREATE INDEX sessions_ip_subnet_hash_idx ON sessions (ip_subnet_hash)';
  EXECUTE 'CREATE INDEX sessions_user_id_device_id_hash_idx ON sessions (user_id, device_id_hash)';
  
  -- 4. Setup pg_partman (1 week partitions, 4 weeks ahead)
  PERFORM partman.create_parent(
    p_parent_table => 'public.sessions',
    p_control => 'expires_at',
    p_interval => '1 week'
  );
  
  -- 5. Configure retention (30 days, drop old partitions)
  UPDATE partman.part_config SET
    retention = '30 days',
    retention_keep_table = false,
    infinite_time_partitions = true
  WHERE parent_table = 'public.sessions';
  
  -- 6. Migrate existing data. Column-name matched with a parity guard: if the hardcoded
  -- createTableSql drifts from the Drizzle-created table, abort the conversion loudly
  -- (rolled back by the outer exception handler) instead of corrupting rows positionally.
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_new
    FROM pg_attribute WHERE attrelid = 'sessions'::regclass AND attnum > 0 AND NOT attisdropped;
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_old
    FROM pg_attribute WHERE attrelid = 'sessions_old'::regclass AND attnum > 0 AND NOT attisdropped;
  IF cols_new IS DISTINCT FROM cols_old THEN
    RAISE EXCEPTION 'sessions: partman createTableSql columns (%) do not match the Drizzle schema (%)', cols_new, cols_old;
  END IF;
  EXECUTE format('INSERT INTO sessions (%s) SELECT %s FROM sessions_old', cols_new, cols_new);

  -- 7. Drop old table
  DROP TABLE sessions_old;
  
  RAISE NOTICE 'sessions table converted to partitioned';
  END IF;


  -- ==========================================================================
  -- TOKENS TABLE: Convert to partitioned
  -- ==========================================================================

  -- Skip if already partitioned
  IF EXISTS (
    SELECT 1 FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'tokens' AND c.relnamespace = 'public'::regnamespace
  ) THEN
    -- Update retention config in case it changed
    UPDATE partman.part_config SET
      retention = '30 days',
      retention_keep_table = false,
      infinite_time_partitions = true
    WHERE parent_table = 'public.tokens';
    RAISE NOTICE 'tokens already partitioned — config updated, skipping conversion';
  ELSE
  -- 1. Rename existing table
  ALTER TABLE tokens RENAME TO tokens_old;
  
  -- 2. Create partitioned table with same structure (dynamic SQL to avoid parse errors)
  EXECUTE 'CREATE TABLE tokens (
    id uuid NOT NULL,
    secret varchar(255) NOT NULL,
    single_use_token varchar(255),
    type varchar NOT NULL,
    email varchar(255) NOT NULL,
    user_id uuid,
    oauth_account_id uuid,
    inactive_membership_id uuid,
    created_by uuid,
    created_at timestamp DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    invoked_at timestamp with time zone,
    CONSTRAINT tokens_id_expires_at_pk PRIMARY KEY (id, expires_at),
    CONSTRAINT tokens_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT tokens_oauth_account_id_oauth_accounts_id_fk FOREIGN KEY (oauth_account_id) REFERENCES oauth_accounts(id) ON DELETE CASCADE,
    CONSTRAINT tokens_created_by_users_id_fk FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
  ) PARTITION BY RANGE (expires_at)';
  
  -- 3. Create indexes
  EXECUTE 'CREATE INDEX tokens_secret_type_idx ON tokens (secret, type)';
  EXECUTE 'CREATE INDEX tokens_user_id_idx ON tokens (user_id)';
  EXECUTE 'CREATE INDEX tokens_created_by_idx ON tokens (created_by)';
  EXECUTE 'CREATE INDEX tokens_single_use_token_idx ON tokens (type, single_use_token)';
  
  -- 4. Setup pg_partman (1 week partitions, 4 weeks ahead)
  PERFORM partman.create_parent(
    p_parent_table => 'public.tokens',
    p_control => 'expires_at',
    p_interval => '1 week'
  );
  
  -- 5. Configure retention (30 days, drop old partitions)
  UPDATE partman.part_config SET
    retention = '30 days',
    retention_keep_table = false,
    infinite_time_partitions = true
  WHERE parent_table = 'public.tokens';
  
  -- 6. Migrate existing data. Column-name matched with a parity guard: if the hardcoded
  -- createTableSql drifts from the Drizzle-created table, abort the conversion loudly
  -- (rolled back by the outer exception handler) instead of corrupting rows positionally.
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_new
    FROM pg_attribute WHERE attrelid = 'tokens'::regclass AND attnum > 0 AND NOT attisdropped;
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_old
    FROM pg_attribute WHERE attrelid = 'tokens_old'::regclass AND attnum > 0 AND NOT attisdropped;
  IF cols_new IS DISTINCT FROM cols_old THEN
    RAISE EXCEPTION 'tokens: partman createTableSql columns (%) do not match the Drizzle schema (%)', cols_new, cols_old;
  END IF;
  EXECUTE format('INSERT INTO tokens (%s) SELECT %s FROM tokens_old', cols_new, cols_new);

  -- 7. Drop old table
  DROP TABLE tokens_old;
  
  RAISE NOTICE 'tokens table converted to partitioned';
  END IF;


  -- ==========================================================================
  -- UNSUBSCRIBE_TOKENS TABLE: Convert to partitioned
  -- ==========================================================================

  -- Skip if already partitioned
  IF EXISTS (
    SELECT 1 FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'unsubscribe_tokens' AND c.relnamespace = 'public'::regnamespace
  ) THEN
    -- Update retention config in case it changed
    UPDATE partman.part_config SET
      retention = '90 days',
      retention_keep_table = false,
      infinite_time_partitions = true
    WHERE parent_table = 'public.unsubscribe_tokens';
    RAISE NOTICE 'unsubscribe_tokens already partitioned — config updated, skipping conversion';
  ELSE
  -- 1. Rename existing table
  ALTER TABLE unsubscribe_tokens RENAME TO unsubscribe_tokens_old;
  
  -- 2. Create partitioned table with same structure (dynamic SQL to avoid parse errors)
  EXECUTE 'CREATE TABLE unsubscribe_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    secret varchar(255) NOT NULL,
    created_at timestamp DEFAULT now() NOT NULL,
    CONSTRAINT unsubscribe_tokens_id_created_at_pk PRIMARY KEY (id, created_at),
    CONSTRAINT unsubscribe_tokens_user_id_users_id_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  ) PARTITION BY RANGE (created_at)';
  
  -- 3. Create indexes
  EXECUTE 'CREATE INDEX unsubscribe_tokens_secret_idx ON unsubscribe_tokens (secret)';
  EXECUTE 'CREATE INDEX unsubscribe_tokens_user_id_idx ON unsubscribe_tokens (user_id)';
  
  -- 4. Setup pg_partman (1 month partitions, 4 weeks ahead)
  PERFORM partman.create_parent(
    p_parent_table => 'public.unsubscribe_tokens',
    p_control => 'created_at',
    p_interval => '1 month'
  );
  
  -- 5. Configure retention (90 days, drop old partitions)
  UPDATE partman.part_config SET
    retention = '90 days',
    retention_keep_table = false,
    infinite_time_partitions = true
  WHERE parent_table = 'public.unsubscribe_tokens';
  
  -- 6. Migrate existing data. Column-name matched with a parity guard: if the hardcoded
  -- createTableSql drifts from the Drizzle-created table, abort the conversion loudly
  -- (rolled back by the outer exception handler) instead of corrupting rows positionally.
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_new
    FROM pg_attribute WHERE attrelid = 'unsubscribe_tokens'::regclass AND attnum > 0 AND NOT attisdropped;
  SELECT string_agg(quote_ident(attname), ', ' ORDER BY attname) INTO cols_old
    FROM pg_attribute WHERE attrelid = 'unsubscribe_tokens_old'::regclass AND attnum > 0 AND NOT attisdropped;
  IF cols_new IS DISTINCT FROM cols_old THEN
    RAISE EXCEPTION 'unsubscribe_tokens: partman createTableSql columns (%) do not match the Drizzle schema (%)', cols_new, cols_old;
  END IF;
  EXECUTE format('INSERT INTO unsubscribe_tokens (%s) SELECT %s FROM unsubscribe_tokens_old', cols_new, cols_new);

  -- 7. Drop old table
  DROP TABLE unsubscribe_tokens_old;
  
  RAISE NOTICE 'unsubscribe_tokens table converted to partitioned';
  END IF;


  -- ==========================================================================
  -- ACTIVITIES TABLE: Convert to partitioned (using LIKE clause)
  -- ==========================================================================
  -- Uses LIKE to clone existing table structure, making it robust to schema changes

  -- Skip if already partitioned
  IF EXISTS (
    SELECT 1 FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'activities' AND c.relnamespace = 'public'::regnamespace
  ) THEN
    -- Update retention config in case it changed
    UPDATE partman.part_config SET
      retention = '90 days',
      retention_keep_table = false,
      infinite_time_partitions = true
    WHERE parent_table = 'public.activities';
    RAISE NOTICE 'activities already partitioned — config updated, skipping conversion';
  ELSE
  -- 1. Create partitioned table cloning structure from Drizzle-created table
  -- Note: We create the partitioned version first, then swap
  EXECUTE 'CREATE TABLE activities_partitioned (LIKE activities INCLUDING DEFAULTS INCLUDING CONSTRAINTS) PARTITION BY RANGE (created_at)';
  
  -- 2. Clone indexes from original table
  FOR r IN 
    SELECT indexdef 
    FROM pg_indexes 
    WHERE tablename = 'activities' 
    AND indexname NOT LIKE '%_pkey'
  LOOP
    -- Replace table name in index definition
    EXECUTE replace(r.indexdef, ' ON activities ', ' ON activities_partitioned ');
  END LOOP;
  
  -- 3. Setup pg_partman (1 week partitions, 4 weeks ahead)
  PERFORM partman.create_parent(
    p_parent_table => 'public.activities_partitioned',
    p_control => 'created_at',
    p_interval => '1 week'
  );
  
  -- 4. Configure retention (90 days, drop old partitions)
  UPDATE partman.part_config SET
    retention = '90 days',
    retention_keep_table = false,
    infinite_time_partitions = true
  WHERE parent_table = 'public.activities_partitioned';
  
  -- 5. Migrate existing data
  INSERT INTO activities_partitioned SELECT * FROM activities;
  
  -- 6. Swap tables atomically
  ALTER TABLE activities RENAME TO activities_old;
  ALTER TABLE activities_partitioned RENAME TO activities;
  
  -- 7. Update partman config to use new table name
  UPDATE partman.part_config SET parent_table = 'public.activities' WHERE parent_table = 'public.activities_partitioned';
  
  -- 8. Drop old table
  DROP TABLE activities_old;
  
  RAISE NOTICE 'activities table converted to partitioned (via LIKE clause)';
  END IF;


  -- ==========================================================================
  -- SEEN_BY TABLE: Convert to partitioned (using LIKE clause)
  -- ==========================================================================
  -- Uses LIKE to clone existing table structure, making it robust to schema changes

  -- Skip if already partitioned
  IF EXISTS (
    SELECT 1 FROM pg_partitioned_table pt
    JOIN pg_class c ON c.oid = pt.partrelid
    WHERE c.relname = 'seen_by' AND c.relnamespace = 'public'::regnamespace
  ) THEN
    -- Update retention config in case it changed
    UPDATE partman.part_config SET
      retention = '90 days',
      retention_keep_table = false,
      infinite_time_partitions = true
    WHERE parent_table = 'public.seen_by';
    RAISE NOTICE 'seen_by already partitioned — config updated, skipping conversion';
  ELSE
  -- 1. Create partitioned table cloning structure from Drizzle-created table
  -- Note: We create the partitioned version first, then swap
  EXECUTE 'CREATE TABLE seen_by_partitioned (LIKE seen_by INCLUDING DEFAULTS INCLUDING CONSTRAINTS) PARTITION BY RANGE (created_at)';
  
  -- 2. Clone indexes from original table
  FOR r IN 
    SELECT indexdef 
    FROM pg_indexes 
    WHERE tablename = 'seen_by' 
    AND indexname NOT LIKE '%_pkey'
  LOOP
    -- Replace table name in index definition
    EXECUTE replace(r.indexdef, ' ON seen_by ', ' ON seen_by_partitioned ');
  END LOOP;
  
  -- 3. Setup pg_partman (1 week partitions, 4 weeks ahead)
  PERFORM partman.create_parent(
    p_parent_table => 'public.seen_by_partitioned',
    p_control => 'created_at',
    p_interval => '1 week'
  );
  
  -- 4. Configure retention (90 days, drop old partitions)
  UPDATE partman.part_config SET
    retention = '90 days',
    retention_keep_table = false,
    infinite_time_partitions = true
  WHERE parent_table = 'public.seen_by_partitioned';
  
  -- 5. Migrate existing data
  INSERT INTO seen_by_partitioned SELECT * FROM seen_by;
  
  -- 6. Swap tables atomically
  ALTER TABLE seen_by RENAME TO seen_by_old;
  ALTER TABLE seen_by_partitioned RENAME TO seen_by;
  
  -- 7. Update partman config to use new table name
  UPDATE partman.part_config SET parent_table = 'public.seen_by' WHERE parent_table = 'public.seen_by_partitioned';
  
  -- 8. Drop old table
  DROP TABLE seen_by_old;
  
  RAISE NOTICE 'seen_by table converted to partitioned (via LIKE clause)';
  END IF;


  -- ==========================================================================
  -- Schedule automatic maintenance
  -- ==========================================================================
  -- pg_partman run_maintenance() should be called periodically.
  -- Options:
  -- 1. pg_cron: schedule run_maintenance_proc() hourly
  -- 2. External scheduler (cron, Cloud Scheduler, etc.)
  -- 3. Neon: pg_partman maintenance runs automatically
  
  RAISE NOTICE 'pg_partman setup complete. Remember to schedule run_maintenance().';

  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Partition setup failed: %. Tables will use regular (non-partitioned) mode with manual cleanup.', SQLERRM;
  END;

END $$;
--> statement-breakpoint
-- ══════════════════════════════════════════════════════════════════════════
-- [rls_setup] RLS — ownership, FORCE RLS, grants
-- ══════════════════════════════════════════════════════════════════════════
-- RLS (Row-Level Security) Setup
-- Configures FORCE RLS, table ownership, and grants.
-- Policies are defined in Drizzle schema files using pgPolicy().
-- RLS enforces tenant-level isolation only; org-level isolation is application-layer (orgGuard).
-- Gracefully skips if required roles are not yet created.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'runtime_role') THEN
    RAISE NOTICE 'Roles not available - skipping RLS setup.';
    RETURN;
  END IF;

  BEGIN
    -- Table ownership and FORCE RLS
    ALTER TABLE attachments OWNER TO admin_role;
    ALTER TABLE yjs_documents OWNER TO admin_role;
    ALTER TABLE activities OWNER TO admin_role;

    ALTER TABLE attachments FORCE ROW LEVEL SECURITY;
    ALTER TABLE yjs_documents FORCE ROW LEVEL SECURITY;

    -- Grants: runtime_role (subject to RLS)
    GRANT SELECT, INSERT, UPDATE, DELETE ON attachments TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON yjs_documents TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON organizations TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON memberships TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON inactive_memberships TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON users TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON sessions TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON user_counters TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON tokens TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON passkeys TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON oauth_accounts TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON totps TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON requests TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON unsubscribe_tokens TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON emails TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON rate_limits TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON channel_counters TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON seen_by TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON product_counters TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON domains TO runtime_role;
    GRANT SELECT, INSERT, UPDATE, DELETE ON tenants TO runtime_role;
    GRANT SELECT ON system_roles TO runtime_role;
    GRANT SELECT ON activities TO runtime_role;

    -- Grants: admin_role (full access; also used by the CDC worker)
    GRANT ALL ON ALL TABLES IN SCHEMA public TO admin_role;
    GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO admin_role;

    -- Grants: pg_catalog usage for JSONB operators
    GRANT USAGE ON SCHEMA pg_catalog TO runtime_role;

    RAISE NOTICE 'RLS setup complete.';
  EXCEPTION WHEN OTHERS THEN
    -- Fail LOUDLY: swallowing this rolled back ownership, FORCE RLS and every grant in
    -- one silent NOTICE — the app then boots with no table grants (every request 403s)
    -- or, worse, without enforced RLS.
    RAISE EXCEPTION 'RLS setup failed: % (SQLSTATE: %)', SQLERRM, SQLSTATE;
  END;
END $$;
--> statement-breakpoint
-- ══════════════════════════════════════════════════════════════════════════
-- [unlogged_setup] UNLOGGED tables
-- ══════════════════════════════════════════════════════════════════════════
-- UNLOGGED Tables Setup
-- Converts ephemeral counter/rate-limit tables to UNLOGGED (skip WAL writes).
-- Idempotent: only alters tables not already UNLOGGED.
-- Gracefully skips if required roles are not yet created.

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_roles WHERE rolname = 'runtime_role') THEN
    RAISE NOTICE 'Skipping UNLOGGED setup - roles not available.';
    RETURN;
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'rate_limits') != 'u' THEN
    ALTER TABLE rate_limits SET UNLOGGED;
    RAISE NOTICE 'rate_limits set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'user_counters') != 'u' THEN
    ALTER TABLE user_counters SET UNLOGGED;
    RAISE NOTICE 'user_counters set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'channel_counters') != 'u' THEN
    ALTER TABLE channel_counters SET UNLOGGED;
    RAISE NOTICE 'channel_counters set to UNLOGGED';
  END IF;

  IF (SELECT relpersistence FROM pg_class WHERE relname = 'product_counters') != 'u' THEN
    ALTER TABLE product_counters SET UNLOGGED;
    RAISE NOTICE 'product_counters set to UNLOGGED';
  END IF;

  RAISE NOTICE 'UNLOGGED setup complete.';
END $$;
