// This file is auto-generated by openapi-parser plugin
import type { GenOperationDetail } from '~/modules/docs/types';

export const tagName = 'attachments' as const;

export const operations: GenOperationDetail[] = [
  {
    operationId: 'syncAttachments',
    responses: [
      {
        status: 200,
        description: 'Success',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'createAttachment',
    responses: [
      {
        status: 201,
        description: 'Attachment',
        schema: {
          type: 'array',
          itemType: 'object',
          ref: '#/components/schemas/Attachment',
          items: {
            type: 'object',
            required: true,
            properties: {
              createdAt: {
                type: 'string',
                required: true,
              },
              id: {
                type: 'string',
                required: true,
              },
              entityType: {
                type: 'string',
                required: true,
                enum: ['attachment'],
              },
              name: {
                type: 'string',
                required: true,
              },
              description: {
                type: ['string', 'null'],
                required: true,
              },
              public: {
                type: 'boolean',
                required: true,
              },
              bucketName: {
                type: 'string',
                required: true,
              },
              groupId: {
                type: ['string', 'null'],
                required: true,
              },
              filename: {
                type: 'string',
                required: true,
              },
              contentType: {
                type: 'string',
                required: true,
              },
              convertedContentType: {
                type: ['string', 'null'],
                required: true,
              },
              size: {
                type: 'string',
                required: true,
              },
              originalKey: {
                type: 'string',
                required: true,
              },
              convertedKey: {
                type: ['string', 'null'],
                required: true,
              },
              thumbnailKey: {
                type: ['string', 'null'],
                required: true,
              },
              createdBy: {
                type: ['string', 'null'],
                required: true,
              },
              modifiedAt: {
                type: ['string', 'null'],
                required: true,
              },
              modifiedBy: {
                type: ['string', 'null'],
                required: true,
              },
              organizationId: {
                type: 'string',
                required: true,
              },
            },
            ref: '#/components/schemas/Attachment',
          },
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'deleteAttachments',
    responses: [
      {
        status: 200,
        description: 'Success',
        schema: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              required: true,
            },
            rejectedItems: {
              type: 'array',
              required: true,
              itemType: 'string',
            },
          },
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'updateAttachment',
    responses: [
      {
        status: 200,
        description: 'Attachment was updated',
        name: 'Attachment',
        ref: '#/components/schemas/Attachment',
        schema: {
          type: 'object',
          properties: {
            createdAt: {
              type: 'string',
              required: true,
            },
            id: {
              type: 'string',
              required: true,
            },
            entityType: {
              type: 'string',
              required: true,
              enum: ['attachment'],
            },
            name: {
              type: 'string',
              required: true,
            },
            description: {
              type: ['string', 'null'],
              required: true,
            },
            public: {
              type: 'boolean',
              required: true,
            },
            bucketName: {
              type: 'string',
              required: true,
            },
            groupId: {
              type: ['string', 'null'],
              required: true,
            },
            filename: {
              type: 'string',
              required: true,
            },
            contentType: {
              type: 'string',
              required: true,
            },
            convertedContentType: {
              type: ['string', 'null'],
              required: true,
            },
            size: {
              type: 'string',
              required: true,
            },
            originalKey: {
              type: 'string',
              required: true,
            },
            convertedKey: {
              type: ['string', 'null'],
              required: true,
            },
            thumbnailKey: {
              type: ['string', 'null'],
              required: true,
            },
            createdBy: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedAt: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedBy: {
              type: ['string', 'null'],
              required: true,
            },
            organizationId: {
              type: 'string',
              required: true,
            },
          },
          ref: '#/components/schemas/Attachment',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'redirectToAttachment',
    responses: [
      {
        status: 200,
        description: 'Success',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
];
