// This file is auto-generated by openapi-parser plugin
import type { GenOperationDetail } from '~/modules/docs/types';

export const tagName = 'entities' as const;

export const operations: GenOperationDetail[] = [
  {
    operationId: 'checkSlug',
    responses: [
      {
        status: 204,
        description: 'Slug is available',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      body: {
        required: true,
        contentType: 'application/json',
        properties: {
          slug: {
            type: 'string',
            required: true,
          },
          entityType: {
            type: 'string',
            required: true,
            enum: ['user', 'organization'],
          },
        },
      },
    },
  },
];
