// This file is auto-generated by openapi-parser plugin
import type { GenOperationDetail } from '~/modules/docs/types';

export const tagName = 'memberships' as const;

export const operations: GenOperationDetail[] = [
  {
    operationId: 'membershipInvite',
    responses: [
      {
        status: 200,
        description: 'Number of sent invitations',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              required: true,
            },
            rejectedItems: {
              type: 'array',
              required: true,
              itemType: 'string',
            },
            invitesSentCount: {
              type: 'number',
              required: true,
            },
          },
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
      query: {
        properties: {
          idOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
          entityType: {
            type: 'string',
            required: true,
            enum: ['organization'],
          },
        },
      },
      body: {
        required: true,
        contentType: 'application/json',
        properties: {
          emails: {
            type: 'array',
            required: true,
            minItems: 1,
            maxItems: 50,
            itemType: 'string',
            format: 'email',
            minLength: 4,
            maxLength: 100,
          },
          role: {
            type: 'string',
            required: true,
            enum: ['member', 'admin'],
          },
        },
      },
    },
  },
  {
    operationId: 'deleteMemberships',
    responses: [
      {
        status: 200,
        description: 'Success',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              required: true,
            },
            rejectedItems: {
              type: 'array',
              required: true,
              itemType: 'string',
            },
          },
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
      query: {
        properties: {
          idOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
          entityType: {
            type: 'string',
            required: true,
            enum: ['organization'],
          },
        },
      },
      body: {
        required: true,
        contentType: 'application/json',
        properties: {
          ids: {
            type: 'array',
            required: true,
            minItems: 1,
            maxItems: 50,
            itemType: 'string',
          },
        },
      },
    },
  },
  {
    operationId: 'updateMembership',
    responses: [
      {
        status: 200,
        description: 'Membership updated',
        name: 'Membership',
        ref: '#/components/schemas/Membership',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            createdAt: {
              type: 'string',
              required: true,
            },
            id: {
              type: 'string',
              required: true,
            },
            contextType: {
              type: 'string',
              required: true,
              enum: ['organization'],
            },
            userId: {
              type: 'string',
              required: true,
            },
            role: {
              type: 'string',
              required: true,
              enum: ['member', 'admin'],
            },
            createdBy: {
              type: 'string',
              required: true,
            },
            modifiedAt: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedBy: {
              type: ['string', 'null'],
              required: true,
            },
            archived: {
              type: 'boolean',
              required: true,
            },
            muted: {
              type: 'boolean',
              required: true,
            },
            order: {
              type: 'number',
              required: true,
              minimum: -140737488355328,
              maximum: 140737488355327,
            },
            organizationId: {
              type: 'string',
              required: true,
            },
            uniqueKey: {
              type: 'string',
              required: true,
            },
          },
          ref: '#/components/schemas/Membership',
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          id: {
            type: 'string',
            required: true,
          },
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
      body: {
        required: false,
        contentType: 'application/json',
        properties: {
          role: {
            type: 'string',
            required: false,
            enum: ['member', 'admin'],
          },
          muted: {
            type: 'boolean',
            required: false,
          },
          archived: {
            type: 'boolean',
            required: false,
          },
          order: {
            type: 'number',
            required: false,
          },
        },
      },
    },
  },
  {
    operationId: 'handleMembershipInvitation',
    responses: [
      {
        status: 200,
        description: 'Invitation was accepted',
        name: 'ContextEntityBase',
        ref: '#/components/schemas/ContextEntityBase',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
              required: true,
            },
            entityType: {
              type: 'string',
              required: true,
              enum: ['organization'],
            },
            slug: {
              type: 'string',
              required: true,
            },
            name: {
              type: 'string',
              required: true,
            },
            createdAt: {
              type: 'string',
              required: true,
            },
            thumbnailUrl: {
              type: ['string', 'null'],
              required: false,
            },
            bannerUrl: {
              type: ['string', 'null'],
              required: false,
            },
          },
          ref: '#/components/schemas/ContextEntityBase',
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          id: {
            type: 'string',
            required: true,
          },
          acceptOrReject: {
            type: 'string',
            required: true,
            enum: ['accept', 'reject'],
          },
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
    },
  },
  {
    operationId: 'getMembers',
    responses: [
      {
        status: 200,
        description: 'Members',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            items: {
              type: 'array',
              required: true,
              itemType: 'object',
              items: {
                type: 'object',
                properties: {
                  createdAt: {
                    type: 'string',
                    required: true,
                  },
                  id: {
                    type: 'string',
                    required: true,
                  },
                  entityType: {
                    type: 'string',
                    required: true,
                    enum: ['user'],
                  },
                  name: {
                    type: 'string',
                    required: true,
                  },
                  description: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  slug: {
                    type: 'string',
                    required: true,
                  },
                  thumbnailUrl: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  bannerUrl: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  email: {
                    type: 'string',
                    required: true,
                    format: 'email',
                  },
                  mfaRequired: {
                    type: 'boolean',
                    required: true,
                  },
                  firstName: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  lastName: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  language: {
                    type: 'string',
                    required: true,
                    enum: ['en', 'nl'],
                  },
                  modifiedAt: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  lastSeenAt: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  lastStartedAt: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  lastSignInAt: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  modifiedBy: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  membership: {
                    type: 'object',
                    required: true,
                    properties: {
                      id: {
                        type: 'string',
                        required: true,
                      },
                      contextType: {
                        type: 'string',
                        required: true,
                        enum: ['organization'],
                      },
                      userId: {
                        type: 'string',
                        required: true,
                      },
                      role: {
                        type: 'string',
                        required: true,
                        enum: ['member', 'admin'],
                      },
                      archived: {
                        type: 'boolean',
                        required: true,
                      },
                      muted: {
                        type: 'boolean',
                        required: true,
                      },
                      order: {
                        type: 'number',
                        required: true,
                        minimum: -140737488355328,
                        maximum: 140737488355327,
                      },
                      organizationId: {
                        type: 'string',
                        required: true,
                      },
                    },
                    ref: '#/components/schemas/MembershipBase',
                  },
                },
              },
            },
            total: {
              type: 'number',
              required: true,
            },
          },
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
      query: {
        properties: {
          q: {
            type: 'string',
            required: false,
          },
          sort: {
            type: 'string',
            required: false,
            enum: ['id', 'name', 'email', 'role', 'createdAt', 'lastSeenAt'],
          },
          order: {
            type: 'string',
            required: false,
            enum: ['asc', 'desc'],
          },
          offset: {
            type: 'string',
            required: false,
          },
          limit: {
            type: 'string',
            required: false,
          },
          idOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
          entityType: {
            type: 'string',
            required: true,
            enum: ['organization'],
          },
          role: {
            type: 'string',
            required: false,
            enum: ['member', 'admin'],
          },
        },
      },
    },
  },
  {
    operationId: 'getPendingMemberships',
    responses: [
      {
        status: 200,
        description: 'Pending memberships',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            items: {
              type: 'array',
              required: true,
              itemType: 'object',
              items: {
                type: 'object',
                properties: {
                  id: {
                    type: 'string',
                    required: true,
                  },
                  email: {
                    type: 'string',
                    required: true,
                    format: 'email',
                  },
                  thumbnailUrl: {
                    type: ['string', 'null'],
                    required: false,
                  },
                  role: {
                    type: ['string', 'null'],
                    required: true,
                    enum: ['member', 'admin', null],
                  },
                  createdAt: {
                    type: 'string',
                    required: true,
                  },
                  createdBy: {
                    type: ['string', 'null'],
                    required: true,
                  },
                },
              },
            },
            total: {
              type: 'number',
              required: true,
            },
          },
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      path: {
        properties: {
          orgIdOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
        },
      },
      query: {
        properties: {
          q: {
            type: 'string',
            required: false,
          },
          sort: {
            type: 'string',
            required: false,
            enum: ['createdAt'],
          },
          order: {
            type: 'string',
            required: false,
            enum: ['asc', 'desc'],
          },
          offset: {
            type: 'string',
            required: false,
          },
          limit: {
            type: 'string',
            required: false,
          },
          idOrSlug: {
            type: 'string',
            required: true,
            description: 'Entity ID or slug. ID is always preferred.',
          },
          entityType: {
            type: 'string',
            required: true,
            enum: ['organization'],
          },
        },
      },
    },
  },
];
