// This file is auto-generated by openapi-parser plugin

export interface ResponseSummary {
  status: number;
  description: string;
}

export interface OperationDetail {
  operationId: string;
  responses: ResponseSummary[];
}

export const tagName = 'organizations' as const;

export const operations: OperationDetail[] = [
  {
    operationId: 'createOrganization',
    responses: [
      {
        status: 201,
        description: 'Organization was created',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getOrganizations',
    responses: [
      {
        status: 200,
        description: 'Organizations',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'deleteOrganizations',
    responses: [
      {
        status: 200,
        description: 'Success',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getOrganization',
    responses: [
      {
        status: 200,
        description: 'Organization',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'updateOrganization',
    responses: [
      {
        status: 200,
        description: 'Organization was updated',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
];
