// This file is auto-generated by openapi-parser plugin
import type { GenOperationDetail } from '~/modules/docs/types';

export const tagName = 'pages' as const;

export const operations: GenOperationDetail[] = [
  {
    operationId: 'syncPages',
    responses: [
      {
        status: 200,
        description: 'Success',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'createPage',
    responses: [
      {
        status: 201,
        description: 'Page',
        name: 'Page',
        ref: '#/components/schemas/Page',
        schema: {
          type: 'object',
          properties: {
            createdAt: {
              type: 'string',
              required: true,
            },
            id: {
              type: 'string',
              required: true,
            },
            entityType: {
              type: 'string',
              required: true,
              enum: ['page'],
            },
            name: {
              type: 'string',
              required: true,
            },
            description: {
              type: 'string',
              required: true,
            },
            keywords: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'string',
              required: true,
              enum: ['unpublished', 'published', 'archived'],
            },
            parentId: {
              type: ['string', 'null'],
              required: true,
            },
            displayOrder: {
              type: 'number',
              required: true,
              minimum: -140737488355328,
              maximum: 140737488355327,
            },
            createdBy: {
              type: 'string',
              required: true,
            },
            modifiedAt: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedBy: {
              type: ['string', 'null'],
              required: true,
            },
          },
          ref: '#/components/schemas/Page',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'getPages',
    responses: [
      {
        status: 200,
        description: 'Pages',
        schema: {
          type: 'object',
          properties: {
            items: {
              type: 'array',
              required: true,
              items: {
                type: 'object',
                required: true,
                properties: {
                  createdAt: {
                    type: 'string',
                    required: true,
                  },
                  id: {
                    type: 'string',
                    required: true,
                  },
                  entityType: {
                    type: 'string',
                    required: true,
                    enum: ['page'],
                  },
                  name: {
                    type: 'string',
                    required: true,
                  },
                  description: {
                    type: 'string',
                    required: true,
                  },
                  keywords: {
                    type: 'string',
                    required: true,
                  },
                  status: {
                    type: 'string',
                    required: true,
                    enum: ['unpublished', 'published', 'archived'],
                  },
                  parentId: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  displayOrder: {
                    type: 'number',
                    required: true,
                    minimum: -140737488355328,
                    maximum: 140737488355327,
                  },
                  createdBy: {
                    type: 'string',
                    required: true,
                  },
                  modifiedAt: {
                    type: ['string', 'null'],
                    required: true,
                  },
                  modifiedBy: {
                    type: ['string', 'null'],
                    required: true,
                  },
                },
                ref: '#/components/schemas/Page',
              },
            },
            total: {
              type: 'number',
              required: true,
            },
          },
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'deletePages',
    responses: [
      {
        status: 204,
        description: 'Page(s) deleted',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'getPage',
    responses: [
      {
        status: 200,
        description: 'Page',
        name: 'Page',
        ref: '#/components/schemas/Page',
        schema: {
          type: 'object',
          properties: {
            createdAt: {
              type: 'string',
              required: true,
            },
            id: {
              type: 'string',
              required: true,
            },
            entityType: {
              type: 'string',
              required: true,
              enum: ['page'],
            },
            name: {
              type: 'string',
              required: true,
            },
            description: {
              type: 'string',
              required: true,
            },
            keywords: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'string',
              required: true,
              enum: ['unpublished', 'published', 'archived'],
            },
            parentId: {
              type: ['string', 'null'],
              required: true,
            },
            displayOrder: {
              type: 'number',
              required: true,
              minimum: -140737488355328,
              maximum: 140737488355327,
            },
            createdBy: {
              type: 'string',
              required: true,
            },
            modifiedAt: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedBy: {
              type: ['string', 'null'],
              required: true,
            },
          },
          ref: '#/components/schemas/Page',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
  {
    operationId: 'updatePage',
    responses: [
      {
        status: 200,
        description: 'Page updated',
        name: 'Page',
        ref: '#/components/schemas/Page',
        schema: {
          type: 'object',
          properties: {
            createdAt: {
              type: 'string',
              required: true,
            },
            id: {
              type: 'string',
              required: true,
            },
            entityType: {
              type: 'string',
              required: true,
              enum: ['page'],
            },
            name: {
              type: 'string',
              required: true,
            },
            description: {
              type: 'string',
              required: true,
            },
            keywords: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'string',
              required: true,
              enum: ['unpublished', 'published', 'archived'],
            },
            parentId: {
              type: ['string', 'null'],
              required: true,
            },
            displayOrder: {
              type: 'number',
              required: true,
              minimum: -140737488355328,
              maximum: 140737488355327,
            },
            createdBy: {
              type: 'string',
              required: true,
            },
            modifiedAt: {
              type: ['string', 'null'],
              required: true,
            },
            modifiedBy: {
              type: ['string', 'null'],
              required: true,
            },
          },
          ref: '#/components/schemas/Page',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [400],
                },
              },
            },
          ],
          ref: '#/components/schemas/BadRequestError',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [401],
                },
              },
            },
          ],
          ref: '#/components/schemas/UnauthorizedError',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [403],
                },
              },
            },
          ],
          ref: '#/components/schemas/ForbiddenError',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [404],
                },
              },
            },
          ],
          ref: '#/components/schemas/NotFoundError',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        schema: {
          type: 'object',
          allOf: [
            {
              type: 'object',
              properties: {
                name: {
                  type: 'string',
                  required: true,
                },
                message: {
                  type: 'string',
                  required: true,
                },
                type: {
                  type: 'string',
                  required: true,
                },
                status: {
                  type: 'integer',
                  required: true,
                  minimum: 400,
                  maximum: 599,
                },
                severity: {
                  type: 'string',
                  required: true,
                  enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
                },
                entityType: {
                  type: 'string',
                  required: false,
                  enum: ['user', 'organization', 'attachment', 'page'],
                },
                logId: {
                  type: 'string',
                  required: false,
                },
                path: {
                  type: 'string',
                  required: false,
                },
                method: {
                  type: 'string',
                  required: false,
                },
                timestamp: {
                  type: 'string',
                  required: false,
                },
                userId: {
                  type: 'string',
                  required: false,
                },
                organizationId: {
                  type: 'string',
                  required: false,
                },
              },
              ref: '#/components/schemas/ApiError',
            },
            {
              type: 'object',
              properties: {
                status: {
                  type: 'number',
                  required: false,
                  enum: [429],
                },
              },
            },
          ],
          ref: '#/components/schemas/TooManyRequestsError',
        },
      },
    ],
  },
];
