// This file is auto-generated by openapi-parser plugin

export interface ResponseSummary {
  status: number;
  description: string;
}

export interface OperationDetail {
  operationId: string;
  responses: ResponseSummary[];
}

export const tagName = 'pages' as const;

export const operations: OperationDetail[] = [
  {
    operationId: 'syncPages',
    responses: [
      {
        status: 200,
        description: 'Success',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'createPage',
    responses: [
      {
        status: 201,
        description: 'Page',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getPages',
    responses: [
      {
        status: 200,
        description: 'Pages',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'deletePages',
    responses: [
      {
        status: 204,
        description: 'Page(s) deleted',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getPage',
    responses: [
      {
        status: 200,
        description: 'Page',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'updatePage',
    responses: [
      {
        status: 200,
        description: 'Page updated',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
];
