// This file is auto-generated by openapi-parser plugin

export interface ResponseSummary {
  status: number;
  description: string;
}

export interface OperationDetail {
  operationId: string;
  responses: ResponseSummary[];
}

export const tagName = 'requests' as const;

export const operations: OperationDetail[] = [
  {
    operationId: 'createRequest',
    responses: [
      {
        status: 201,
        description: 'Requests',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getRequests',
    responses: [
      {
        status: 200,
        description: 'Requests',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'deleteRequests',
    responses: [
      {
        status: 204,
        description: 'Requests deleted',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
];
