// This file is auto-generated by openapi-parser plugin
import type { GenOperationDetail } from '~/modules/docs/types';

export const tagName = 'system' as const;

export const operations: GenOperationDetail[] = [
  {
    operationId: 'systemInvite',
    responses: [
      {
        status: 200,
        description: 'Invitations are sent',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            success: {
              type: 'boolean',
              required: true,
            },
            rejectedItems: {
              type: 'array',
              required: true,
              itemType: 'string',
            },
            invitesSentCount: {
              type: 'number',
              required: true,
            },
          },
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          refDescription: 'Error returned when the request is malformed or contains invalid data.',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          refDescription: 'Error returned when authentication is missing or invalid.',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          refDescription: 'Error returned when the user lacks permission for the requested action.',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          refDescription: 'Error returned when the requested resource cannot be found.',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          refDescription: 'Error returned when rate limits are exceeded.',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      body: {
        required: true,
        contentType: 'application/json',
        properties: {
          emails: {
            type: 'array',
            required: true,
            minItems: 1,
            maxItems: 50,
            itemType: 'string',
            format: 'email',
          },
        },
      },
    },
  },
  {
    operationId: 'getPresignedUrl',
    responses: [
      {
        status: 200,
        description: 'Presigned URL',
        contentType: 'application/json',
        schema: {
          type: 'string',
          contentType: 'application/json',
        },
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          refDescription: 'Error returned when the request is malformed or contains invalid data.',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          refDescription: 'Error returned when authentication is missing or invalid.',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          refDescription: 'Error returned when the user lacks permission for the requested action.',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          refDescription: 'Error returned when the requested resource cannot be found.',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          refDescription: 'Error returned when rate limits are exceeded.',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      query: {
        properties: {
          key: {
            type: 'string',
            required: true,
          },
          isPublic: {
            type: 'object',
            required: false,
            anyOf: [
              {
                type: 'boolean',
                required: false,
              },
              {
                type: 'string',
                required: false,
              },
            ],
          },
        },
      },
    },
  },
  {
    operationId: 'paddleWebhook',
    responses: [
      {
        status: 204,
        description: 'Paddle webhook received',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          refDescription: 'Error returned when the request is malformed or contains invalid data.',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          refDescription: 'Error returned when authentication is missing or invalid.',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          refDescription: 'Error returned when the user lacks permission for the requested action.',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          refDescription: 'Error returned when the requested resource cannot be found.',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          refDescription: 'Error returned when rate limits are exceeded.',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      body: {
        required: false,
        contentType: 'application/json',
      },
    },
  },
  {
    operationId: 'sendNewsletter',
    responses: [
      {
        status: 204,
        description: 'Newsletter sent',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
        name: 'BadRequestError',
        ref: '#/components/responses/BadRequestError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [400],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/BadRequestError',
          refDescription: 'Error returned when the request is malformed or contains invalid data.',
          contentType: 'application/json',
        },
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
        name: 'UnauthorizedError',
        ref: '#/components/responses/UnauthorizedError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [401],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/UnauthorizedError',
          refDescription: 'Error returned when authentication is missing or invalid.',
          contentType: 'application/json',
        },
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
        name: 'ForbiddenError',
        ref: '#/components/responses/ForbiddenError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [403],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/ForbiddenError',
          refDescription: 'Error returned when the user lacks permission for the requested action.',
          contentType: 'application/json',
        },
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
        name: 'NotFoundError',
        ref: '#/components/responses/NotFoundError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [404],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/NotFoundError',
          refDescription: 'Error returned when the requested resource cannot be found.',
          contentType: 'application/json',
        },
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
        name: 'TooManyRequestsError',
        ref: '#/components/responses/TooManyRequestsError',
        contentType: 'application/json',
        schema: {
          type: 'object',
          properties: {
            name: {
              type: 'string',
              required: true,
            },
            message: {
              type: 'string',
              required: true,
            },
            type: {
              type: 'string',
              required: true,
            },
            status: {
              type: 'number',
              required: true,
              enum: [429],
            },
            severity: {
              type: 'string',
              required: true,
              enum: ['fatal', 'error', 'warn', 'info', 'debug', 'trace'],
            },
            entityType: {
              type: 'string',
              required: false,
              enum: ['user', 'organization', 'attachment', 'page'],
            },
            logId: {
              type: 'string',
              required: false,
            },
            path: {
              type: 'string',
              required: false,
            },
            method: {
              type: 'string',
              required: false,
            },
            timestamp: {
              type: 'string',
              required: false,
            },
            userId: {
              type: 'string',
              required: false,
            },
            organizationId: {
              type: 'string',
              required: false,
            },
          },
          extendsRef: '#/components/schemas/ApiError',
          ref: '#/components/schemas/TooManyRequestsError',
          refDescription: 'Error returned when rate limits are exceeded.',
          contentType: 'application/json',
        },
      },
    ],
    request: {
      query: {
        properties: {
          toSelf: {
            type: 'object',
            required: false,
            anyOf: [
              {
                type: 'string',
                required: false,
              },
              {
                type: 'boolean',
                required: false,
              },
            ],
          },
        },
      },
      body: {
        required: true,
        contentType: 'application/json',
        properties: {
          organizationIds: {
            type: 'array',
            required: true,
            itemType: 'string',
          },
          roles: {
            type: 'array',
            required: true,
            minItems: 1,
            itemType: 'string',
            enum: ['member', 'admin'],
          },
          subject: {
            type: 'string',
            required: true,
          },
          content: {
            type: 'string',
            required: true,
          },
        },
      },
    },
  },
];
