import { useThemeStore } from '~/store/theme';

type FeatureProps = {
  title: string;
  description: string;
  icon: string;
  invertClass: string;
};

const features = [
  {
    title: 'Hono & NodeJS',
    description: 'A simple, fast server. Web standards, RPC support and great middleware.',
    icon: 'hono',
  },
  {
    title: 'React',
    description: 'React + i18Next. Zustand to manage state.',
    icon: 'react',
  },
  {
    title: 'Database',
    description: 'Postgres DB with Drizzle ORM. Seeds and easy migrations.',
    icon: 'drizzle',
  },
  {
    title: 'Components',
    description: 'Shadcn UI components built with Radix UI and Tailwind CSS.',
    icon: 'tailwind',
  },
  {
    title: 'Authentication',
    description: 'Authentication with Lucia Auth. CASL for authorization flows.',
    icon: 'authentication',
  },
  {
    title: 'API Docs',
    description: 'Autogenerated OpenAPI docs based on Zod schemas.',
    icon: 'openapi',
  },
  {
    title: 'Vite & Turborepo',
    description: 'A fast build process for your monorepo. Also uses Vite PWA.',
    icon: 'vite',
  },
  {
    title: 'Tanstack',
    description: 'Tanstack Router, Query and its popular Table for data-rich solutions.',
    icon: 'tanstack',
  },
  {
    title: 'And more !',
    description: 'Storybook for your UI. React Email. Biome for formatting.',
    icon: 'plus',
  },
];

const Feature = ({ title, description, icon, invertClass }: FeatureProps) => (
  <div className="bg-card relative overflow-hidden rounded-lg p-2">
    <div className="flex h-[180px] flex-col justify-between rounded-md p-6">
      <img src={`/features/${icon}.svg`} alt={title} className={`h-12 w-12 object-contain ${invertClass}`} loading="lazy" />
      <div className="space-y-2">
        <h3 className="font-medium">{title}</h3>
        <p className="text-muted-foreground text-sm">{description}</p>
      </div>
    </div>
  </div>
);

import { ArrowDown } from 'lucide-react';
import { useState } from 'react';
import { Badge } from '~/components/ui/badge';
import { Button } from '~/components/ui/button';
import { useMediaQuery } from '../../hooks/useMediaQuery';

const Features = () => {
  const { mode } = useThemeStore();
  const invertClass = mode === 'dark' ? 'invert' : '';
  const isMobile = useMediaQuery('(max-width: 768px)');

  const [showAllFeatures, setShowAllFeatures] = useState(!isMobile);

  const visibleFeatures = showAllFeatures ? features : features.slice(0, 4);

  const handleLoadMore = () => {
    setShowAllFeatures(true);
  };

  return (
    <>
      <div className="mx-auto grid max-w-[64rem] justify-center gap-4 sm:grid-cols-2 md:grid-cols-3">
        {visibleFeatures.map((feature) => (
          <Feature key={feature.title} {...feature} invertClass={invertClass} />
        ))}
      </div>

      {!showAllFeatures && features.length > 4 && (
        <Button variant="ghost" className="w-full mt-4" onClick={handleLoadMore}>
          <Badge className="mr-2">5</Badge>
          more features
          <ArrowDown className="ml-2" size={16} />
        </Button>
      )}
    </>
  );
};

export default Features;
