-- ⚠️ AUTO-GENERATED — DO NOT EDIT THIS FILE DIRECTLY
-- This migration is generated by a script in backend/scripts/migrations/.
-- To make changes, edit the generator script and re-run it.
-- The user will handle migration generation and application.
--
-- CDC (Change Data Capture) Setup
-- Sets up PostgreSQL logical replication for the activities CDC worker.
-- Requires: wal_level=logical (see compose.yaml)
-- Gracefully skips if logical replication is not available.

DO $$
BEGIN
  -- Check if pg_publication is available
  IF NOT EXISTS (SELECT 1 FROM pg_catalog.pg_class WHERE relname = 'pg_publication') THEN
    RAISE NOTICE 'Logical replication not available - skipping CDC setup.';
    RETURN;
  END IF;

  -- 1. Create or update publication
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'cdc_pub') THEN
      CREATE PUBLICATION cdc_pub FOR TABLE users, organizations, attachments, requests, memberships, inactive_memberships, tenants;
      RAISE NOTICE 'Created publication cdc_pub';
    ELSE
      -- Publication exists — replace with current table list
      RAISE NOTICE 'Publication cdc_pub already exists, syncing tables...';
      ALTER PUBLICATION cdc_pub SET TABLE users, organizations, attachments, requests, memberships, inactive_memberships, tenants;
      RAISE NOTICE 'Publication tables synced';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Publication setup failed: % (SQLSTATE: %)', SQLERRM, SQLSTATE;
  END;

  -- 2. Set REPLICA IDENTITY FULL (separate block)
  BEGIN
    ALTER TABLE users REPLICA IDENTITY FULL;
    ALTER TABLE organizations REPLICA IDENTITY FULL;
    ALTER TABLE attachments REPLICA IDENTITY FULL;
    ALTER TABLE requests REPLICA IDENTITY FULL;
    ALTER TABLE memberships REPLICA IDENTITY FULL;
    ALTER TABLE inactive_memberships REPLICA IDENTITY FULL;
    ALTER TABLE tenants REPLICA IDENTITY FULL;
    RAISE NOTICE 'REPLICA IDENTITY FULL set on all tracked tables';
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'REPLICA IDENTITY setup failed: % (SQLSTATE: %)', SQLERRM, SQLSTATE;
  END;

  -- 3. Create replication slot (separate block - may fail on managed providers)
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_replication_slots WHERE slot_name = 'cdc_slot') THEN
      PERFORM pg_create_logical_replication_slot('cdc_slot', 'pgoutput');
      RAISE NOTICE 'Created replication slot cdc_slot';
    ELSE
      RAISE NOTICE 'Replication slot cdc_slot already exists';
    END IF;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'Replication slot setup failed: % (SQLSTATE: %). Worker will create it at startup.', SQLERRM, SQLSTATE;
  END;

  RAISE NOTICE 'CDC setup complete.';
END $$;
