// This file is auto-generated by openapi-parser plugin

export interface ResponseSummary {
  status: number;
  description: string;
}

export interface OperationDetail {
  operationId: string;
  responses: ResponseSummary[];
}

export const tagName = 'system' as const;

export const operations: OperationDetail[] = [
  {
    operationId: 'systemInvite',
    responses: [
      {
        status: 200,
        description: 'Invitations are sent',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'getPresignedUrl',
    responses: [
      {
        status: 200,
        description: 'Presigned URL',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'paddleWebhook',
    responses: [
      {
        status: 204,
        description: 'Paddle webhook received',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
  {
    operationId: 'sendNewsletter',
    responses: [
      {
        status: 204,
        description: 'Newsletter sent',
      },
      {
        status: 400,
        description: 'Bad request: problem processing request.',
      },
      {
        status: 401,
        description: 'Unauthorized: authentication required.',
      },
      {
        status: 403,
        description: 'Forbidden: insufficient permissions.',
      },
      {
        status: 404,
        description: 'Not found: resource does not exist.',
      },
      {
        status: 429,
        description: 'Rate limit: too many requests.',
      },
    ],
  },
];
