import type { OpenAPIRegistry } from '@asteasolutions/zod-to-openapi';

/**
 * OpenAPI tag ids, also used in activities table.
 */
export const openapiTagIds = [
  'me',
  'users',
  'memberships',
  'organizations',
  'requests',
  'entities',
  'system',
  'auth',
  'attachments',
  'pages',
  'metrics',
  'activities',
  'tenants',
  'seen',
] as const;

export type OpenApiTagId = (typeof openapiTagIds)[number];

/**
 * Tag descriptions for OpenAPI documentation.
 */
const tagDescriptions: Record<OpenApiTagId, string> = {
  me: `Operations scoped to the current user (the user associated with the active session). Includes
        profile management, session control, MFA toggling, upload token generation, viewing and responding
        to membership invitations, leaving entities, and email unsubscription. Distinct from \`users\`
        operations, which target any user in the system.`,

  users: `Read-only operations for listing and retrieving users within an organization context. Write
        operations on users are handled by the \`me\` (self) and \`system\` (admin) modules.`,

  memberships: `Operations for managing memberships, which represent relationships between a user and a
        context entity (e.g., an organization). Includes inviting users, accepting or rejecting invitations,
        updating role and status flags (archived, muted), listing members and pending invitations, and
        removing memberships.`,

  organizations: `Operations for managing organizations, which are core context entities and the highest
        ancestor in the entity hierarchy. Supports creating, listing, retrieving, updating, and deleting
        organizations within a tenant. Cross-tenant listing is available with elevated permissions.`,

  requests: `Operations for handling public form submissions such as contact messages, newsletter signups,
        and waitlist entries. Submission is public with bot protection and rate limiting. Listing and
        deletion require system admin access.`,

  entities: `Cross-cutting operations that apply across multiple entity types. Includes slug availability
        checking and real-time SSE streaming (both a public stream for unauthenticated entity updates and
        an authenticated app stream for per-user entity and membership notifications).`,

  system: `System admin operations for platform-wide user management. Includes listing, updating, and
        deleting users, sending system-level invitations, sending newsletters, and handling payment
        webhooks.`,

  auth: `Authentication operations supporting multiple sign-in methods: email/password, OAuth (GitHub,
        Google, Microsoft), passkeys (WebAuthn), and TOTP. Covers sign-up, sign-in, sign-out, password
        reset, token invocation, email checking, admin impersonation, and MFA credential management.`,

  attachments: `Operations for managing file-based attachments (e.g., images, documents) linked to entities.
        Files are uploaded directly by the client to S3; the API handles metadata registration, retrieval,
        updates, deletion of records, and presigned URL generation for private files.`,

  pages: `Operations for managing pages, which are content entities with public read access. Read operations
        are publicly available with caching. Write operations (create, update, delete) require system admin
        access and are scoped to a tenant.`,

  metrics: `Operations for retrieving system-level statistics and observability data. Includes public entity
        counts (cached, with bot protection), raw system metrics, Node.js runtime metrics, entity cache
        stats, and CDC sync pipeline metrics. Detailed metrics require system admin access.`,

  activities: `Operations for retrieving activities (audit log entries). Activities track create, update, and
        delete events across all resources. Read-only, system admin access only.`,

  tenants: `System admin operations for managing tenants. Tenants are top-level isolation boundaries used by
        Row-Level Security (RLS) to partition data. Supports listing, retrieving, creating, updating, and
        soft-deleting (archiving) tenants.`,

  seen: `Operations for tracking which product entities a user has viewed. Supports batch marking entities
        as seen (deduplicating against existing records) and incrementing view counts. Used to power unseen
        count badges in navigation and view count columns in entity lists.`,
};

/**
 * Predefined OpenAPI tags for the API documentation.
 * Derived from openapiTagIds with descriptions.
 */
export const openapiTags = openapiTagIds.map((name) => ({
  name,
  description: tagDescriptions[name],
}));

/**
 * Allows registering app-specific OpenAPI schemas.
 * These schemas will be generated by openapi-ts on frontend
 * and included in generated OpenAPI documentation.
 */
export const registerAppSchema = (_registry: OpenAPIRegistry) => {
  // Register any app-specific schemas here
};
